# dcf
# Caminho: Catálogo > Biblioteca de scripts > dcf
# Fonte: Gestão_de_Pessoas_-_Benefícios_Versão_90_Reembolso.xml (5 variantes entre os XMLs; esta é a mais recente)

import clr
import System
clr.AddReference("System.Data")
from System.Data import DataSet 
clr.AddReference("Newtonsoft.Json")
from Newtonsoft.Json import * 
from System.Text import StringBuilder
from System.Web import *

from Newtonsoft.Json import JsonConvert
from Newtonsoft.Json.Linq import JArray, JValue

from Venki.Supravizio.Processo.Custom import OrdemServico
from Venki.Supravizio.Processo.Custom import Servico
from Venki.Supravizio.Recurso.Custom import Pessoa
from System import Convert
        

# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# NEW STUFFS

# T O D O S   O S   C H A M A D O S ABERTOS
def listarChamadosAbertos():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_ULT_ATUA, PESSOA.NOME As RESPONSAVEL, OCORRENCIA.ID_CLASSE_SUB_PROC_INI As IDENTIFICADOR_PROCESSO, PESSOA.USUARIO_REDE, Coalesce(CPE_CSC.CSC_DGCO, CPE_CSC.NUMERO_DGCO, CPE_FINANCEIRO.DGCO_BB) As CSC_DGCO, OCORRENCIA.ID_OCORRENCIA, CLASSE_SUB_PROCESSO.SIGLA,FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' AS TEMPO_EM_ABERTO From OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Where OCORRENCIA.SITUACAO = 'Aberto' And (CLASSE_SUB_PROCESSO.SIGLA In ('ADT', 'ANGACOL', 'ANALISEPROJETOBASICO', 'ALTERARDADOSBANCARIOS', 'AVFOR', 'AVALIAFISCASERVICOOO', 'ROTINAAVALIACAO', 'AVSENCERRACONTRATO', 'DESIGNASISCCON2', 'DESIGNACAOSISCONNN', '423', 'DISTRATOERESCI', 'EMISSAOATESTADOFORNECEDOR', 'NOTIFICAFORNECEDORADITAMENTO2', 'ONBOARD', 'PROCESSADM', 'REVISAOOC', 'TERMOACEITEDESIGNACAOO', 'TERMOINTERVCONTRAT', 'ANAGARANCONT', 'AUTORIZARALTDADOSBANC', 'AVALIFORNECEDORES', 'AVISOENCERRACONT', 'DESIGNACAODEINTERVENIENTES', 'DISTRATOERESCISAO', 'ATESTADOCAPTECFORNECEDOR', 'NOTIFICACOESFORNECEDOR', 'ADITAMENTOSOL', 'TERMODEDESIGNACAO', 'ENCERRAMENTODECONTRATO', 'INSERIRDOCSGESCON') or OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (600, 379, 395, 598, 380, 536, 357, 348, 625, 637, 654, 635, 641, 659, 658, 640, 655, 404, 327, 346))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:  
        return "Erro ao executar a consulta: " + str(e)



# T O D O S   O S   C H A M A D O S
def listarChamados():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, OCORRENCIA.DATA_HORA_ULT_ATUA, PESSOA.NOME As RESPONSAVEL, OCORRENCIA.ID_CLASSE_SUB_PROC_INI As IDENTIFICADOR_PROCESSO, PESSOA.USUARIO_REDE, Coalesce(CPE_CSC.CSC_DGCO, CPE_CSC.NUMERO_DGCO, CPE_FINANCEIRO.DGCO_BB) As CSC_DGCO, OCORRENCIA.ID_OCORRENCIA, CLASSE_SUB_PROCESSO.SIGLA, FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' AS TEMPO_TRATAMENTO From OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Where OCORRENCIA.SITUACAO != 'Aberto' And (CLASSE_SUB_PROCESSO.SIGLA In ('ADT', 'ANGACOL', 'ANALISEPROJETOBASICO', 'ALTERARDADOSBANCARIOS', 'AVSENCERRACONTRATO', '423', 'DISTRATOERESCI', 'EMISSAOATESTADOFORNECEDOR', 'NOTIFICAFORNECEDORADITAMENTO2', 'PROCESSADM', 'REVISAOOC', 'ANAGARANCONT', 'AUTORIZARALTDADOSBANC', 'AVISOENCERRACONT', 'DISTRATOERESCISAO', 'ATESTADOCAPTECFORNECEDOR', 'NOTIFICACOESFORNECEDOR', 'ADITAMENTOSOL', 'ENCERRAMENTODECONTRATO', 'INSERIRDOCSGESCON') or OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (600, 379, 395, 598, 380, 536, 357, 348, 625, 659, 404, 327, 346))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)





# S O L I C I T A Ç Õ E S   D E   N O T I F I C A Ç Ã O
def listarSolicitacoesNotificacao():
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_ULT_ATUA, CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CPE_CSC.OBJETO_CONTRATO, CPE_CSC.CSC_DATA_FIM, CPE_CSC.CSC_DGCO, CPE_CSC.OBSERVACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME AS FISCAL_DE_SERVICO, PESSOA1.NOME AS FISCAL_ADM_DO_CONTRATO, PESSOA2.NOME AS GESTOR_DO_CONTRATO, OCORRENCIA.ID_OCORRENCIA, PESSOA3.NOME AS RESPONSAVEL, PESSOA3.USUARIO_REDE AS USUARIO_RESPONSAVEL, CLASSE_SUB_PROCESSO.SIGLA, CPE_CONTRATOS02.CLAUSULA_CONTRATUAL_DESCUMPRIDA, CASE WHEN OCORRENCIA.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO,VERSAO_APROVACAO.VERSAO AS VERSAO_APROVACAO, APROVACAO.ID_ASSUNTO_APROVACAO, APROVACAO.SITUACAO AS SITUACAO_APROVACAO, VERSAO_APROVACAO.SITUACAO AS SITUACAO_VERSAO_APROVACAO, APROVACAO.MOTIVO AS MOTIVO_APROVACAO, VERSAO_APROVACAO.DATA_HORA_CRIACAO AS DATA_HORA_CRIACAO_VERSAO,PESSOA4.NOME AS APROVADOR FROM OCORRENCIA LEFT JOIN CLASSE_SUB_PROCESSO ON CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = OCORRENCIA.ID_CLASSE_SUB_PROC_INI LEFT JOIN CPE_CSC ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN PESSOA ON PESSOA.ID_PESSOA = CPE_CSC.FISCAL_DE_SERVICO LEFT JOIN PESSOA PESSOA1 ON PESSOA1.ID_PESSOA = CPE_CSC.FISCAL_ADM_DO_CONTRATO LEFT JOIN PESSOA PESSOA2 ON PESSOA2.ID_PESSOA = CPE_CSC.GESTOR_DO_CONTRATO LEFT JOIN PESSOA PESSOA3 ON PESSOA3.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL LEFT JOIN CPE_CONTRATOS02 ON OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA LEFT JOIN ASSUNTO_APROVACAO ON OCORRENCIA.ID_OCORRENCIA = ASSUNTO_APROVACAO.ID_OCORRENCIA LEFT JOIN APROVACAO ON APROVACAO.ID_ASSUNTO_APROVACAO = ASSUNTO_APROVACAO.ID_ASSUNTO_APROVACAO LEFT JOIN VERSAO_APROVACAO ON VERSAO_APROVACAO.ID_ASSUNTO_APROVACAO = ASSUNTO_APROVACAO.ID_ASSUNTO_APROVACAO LEFT JOIN PESSOA PESSOA4 ON APROVACAO.ID_PESSOA = PESSOA4.ID_PESSOA WHERE (CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO IN (600) OR CLASSE_SUB_PROCESSO.SIGLA IN ('NOTIFICAFORNECEDORADITAMENTO2', 'NOTIFICACOESFORNECEDOR'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesSolicitacaoNotificacao(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_ULT_ATUA, CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CPE_CSC.OBJETO_CONTRATO, CPE_CSC.CSC_DATA_FIM, CPE_CSC.CSC_DGCO, CPE_CSC.OBSERVACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME AS FISCAL_DE_SERVICO, PESSOA1.NOME AS FISCAL_ADM_DO_CONTRATO, PESSOA2.NOME AS GESTOR_DO_CONTRATO, OCORRENCIA.ID_OCORRENCIA, PESSOA3.NOME AS RESPONSAVEL, PESSOA3.USUARIO_REDE AS USUARIO_RESPONSAVEL, CLASSE_SUB_PROCESSO.SIGLA, CPE_CONTRATOS02.CLAUSULA_CONTRATUAL_DESCUMPRIDA, CASE WHEN OCORRENCIA.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO,VERSAO_APROVACAO.VERSAO AS VERSAO_APROVACAO, APROVACAO.ID_ASSUNTO_APROVACAO, APROVACAO.SITUACAO AS SITUACAO_APROVACAO, VERSAO_APROVACAO.SITUACAO AS SITUACAO_VERSAO_APROVACAO, APROVACAO.MOTIVO AS MOTIVO_APROVACAO, VERSAO_APROVACAO.DATA_HORA_CRIACAO AS DATA_HORA_CRIACAO_VERSAO,PESSOA4.NOME AS APROVADOR FROM OCORRENCIA LEFT JOIN CLASSE_SUB_PROCESSO ON CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = OCORRENCIA.ID_CLASSE_SUB_PROC_INI LEFT JOIN CPE_CSC ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN PESSOA ON PESSOA.ID_PESSOA = CPE_CSC.FISCAL_DE_SERVICO LEFT JOIN PESSOA PESSOA1 ON PESSOA1.ID_PESSOA = CPE_CSC.FISCAL_ADM_DO_CONTRATO LEFT JOIN PESSOA PESSOA2 ON PESSOA2.ID_PESSOA = CPE_CSC.GESTOR_DO_CONTRATO LEFT JOIN PESSOA PESSOA3 ON PESSOA3.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL LEFT JOIN CPE_CONTRATOS02 ON OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA LEFT JOIN ASSUNTO_APROVACAO ON OCORRENCIA.ID_OCORRENCIA = ASSUNTO_APROVACAO.ID_OCORRENCIA LEFT JOIN APROVACAO ON APROVACAO.ID_ASSUNTO_APROVACAO = ASSUNTO_APROVACAO.ID_ASSUNTO_APROVACAO LEFT JOIN VERSAO_APROVACAO ON VERSAO_APROVACAO.ID_ASSUNTO_APROVACAO = ASSUNTO_APROVACAO.ID_ASSUNTO_APROVACAO LEFT JOIN PESSOA PESSOA4 ON APROVACAO.ID_PESSOA = PESSOA4.ID_PESSOA WHERE (CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO IN (600) OR CLASSE_SUB_PROCESSO.SIGLA IN ('NOTIFICAFORNECEDORADITAMENTO2', 'NOTIFICACOESFORNECEDOR')) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)






# S O L I C I T A Ç Õ E S   D E   A D I T A M E N T O
def listarSolicitacoesAditamento():
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_ULT_ATUA, CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO, OCORRENCIA.DATA_HORA_SOL, CPE_CSC.OBJETO_CONTRATO, CPE_CSC.CSC_DATA_FIM, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, CASE WHEN CPE_CSC.CSC_DGCO IS NOT NULL THEN CPE_CSC.CSC_DGCO ELSE CPE_FINANCEIRO.DGCO_BB END AS CSC_DGCO, CPE_CSC.OBSERVACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME AS FISCAL_DE_SERVICO, PESSOA1.NOME AS FISCAL_ADM_DO_CONTRATO, PESSOA2.NOME AS GESTOR_DO_CONTRATO, OCORRENCIA.ID_OCORRENCIA, PESSOA3.NOME AS RESPONSAVEL, PESSOA3.USUARIO_REDE AS USUARIO_RESPONSAVEL, CLASSE_SUB_PROCESSO.SIGLA, CPE_CSC.NUMERO_RC, Z_00143_ADIT_SOL.LIST_AD AS TIPO_ADITAMENTO, CPE_FINANCEIRO.DGCO_BB, CASE WHEN OCORRENCIA.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO FROM OCORRENCIA LEFT JOIN CLASSE_SUB_PROCESSO ON CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = OCORRENCIA.ID_CLASSE_SUB_PROC_INI LEFT JOIN CPE_CSC ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN PESSOA ON PESSOA.ID_PESSOA = CPE_CSC.FISCAL_DE_SERVICO LEFT JOIN PESSOA PESSOA1 ON PESSOA1.ID_PESSOA = CPE_CSC.FISCAL_ADM_DO_CONTRATO LEFT JOIN PESSOA PESSOA2 ON PESSOA2.ID_PESSOA = CPE_CSC.GESTOR_DO_CONTRATO LEFT JOIN PESSOA PESSOA3 ON PESSOA3.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL LEFT JOIN Z_00143_ADIT_SOL ON OCORRENCIA.ID_OCORRENCIA = Z_00143_ADIT_SOL.ID_OCORRENCIA LEFT JOIN CPE_FINANCEIRO ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA WHERE (CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO IN (379) OR CLASSE_SUB_PROCESSO.SIGLA IN ('ADT', 'ADITAMENTOSOL'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesSolicitacaoAditamento(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_ULT_ATUA, CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO, OCORRENCIA.DATA_HORA_SOL, CPE_CSC.OBJETO_CONTRATO, CPE_CSC.CSC_DATA_FIM, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, CASE WHEN CPE_CSC.CSC_DGCO IS NOT NULL THEN CPE_CSC.CSC_DGCO ELSE CPE_FINANCEIRO.DGCO_BB END AS CSC_DGCO, CPE_CSC.OBSERVACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME AS FISCAL_DE_SERVICO, PESSOA1.NOME AS FISCAL_ADM_DO_CONTRATO, PESSOA2.NOME AS GESTOR_DO_CONTRATO, OCORRENCIA.ID_OCORRENCIA, PESSOA3.NOME AS RESPONSAVEL, PESSOA3.USUARIO_REDE AS USUARIO_RESPONSAVEL, CLASSE_SUB_PROCESSO.SIGLA, CPE_CSC.NUMERO_RC, Z_00143_ADIT_SOL.LIST_AD AS TIPO_ADITAMENTO, CPE_FINANCEIRO.DGCO_BB, CASE WHEN OCORRENCIA.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO FROM OCORRENCIA LEFT JOIN CLASSE_SUB_PROCESSO ON CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = OCORRENCIA.ID_CLASSE_SUB_PROC_INI LEFT JOIN CPE_CSC ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN PESSOA ON PESSOA.ID_PESSOA = CPE_CSC.FISCAL_DE_SERVICO LEFT JOIN PESSOA PESSOA1 ON PESSOA1.ID_PESSOA = CPE_CSC.FISCAL_ADM_DO_CONTRATO LEFT JOIN PESSOA PESSOA2 ON PESSOA2.ID_PESSOA = CPE_CSC.GESTOR_DO_CONTRATO LEFT JOIN PESSOA PESSOA3 ON PESSOA3.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL LEFT JOIN Z_00143_ADIT_SOL ON OCORRENCIA.ID_OCORRENCIA = Z_00143_ADIT_SOL.ID_OCORRENCIA LEFT JOIN CPE_FINANCEIRO ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA WHERE (CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO IN (379) OR CLASSE_SUB_PROCESSO.SIGLA IN ('ADT', 'ADITAMENTOSOL')) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



# R E V I S Õ E S   D E   O C
def listarRevisoesOrdensCompra():
    try:
        result_table2 = DB.ExecuteDataTable("WITH AA_ULTIMO AS (SELECT AA1.ID_OCORRENCIA, MAX(AA1.ID_ASSUNTO_APROVACAO) AS ID_ASSUNTO_APROVACAO FROM ASSUNTO_APROVACAO AA1 GROUP BY AA1.ID_OCORRENCIA), ULTIMO_APROVADOR AS (SELECT AAU.ID_OCORRENCIA, P.NOME AS APROVADOR FROM AA_ULTIMO AAU JOIN (SELECT A.ID_ASSUNTO_APROVACAO, A.ID_PESSOA, ROW_NUMBER() OVER (PARTITION BY A.ID_ASSUNTO_APROVACAO ORDER BY A.DATA_HORA_EVIDENCIA DESC) AS RN FROM APROVACAO A) A1 ON A1.ID_ASSUNTO_APROVACAO = AAU.ID_ASSUNTO_APROVACAO AND A1.RN = 1 JOIN PESSOA P ON P.ID_PESSOA = A1.ID_PESSOA) SELECT O.ASSUNTO, O.DATA_HORA_SOL, O.ID_CLASSE_SUB_PROC_INI, O.NUMERO, O.SITUACAO, O.DATA_HORA_ULT_ATUA, O.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, O.ID_OCORRENCIA, OS.DESCRICAO_DETALHADA, CP.CNPJ, CP.NOME_FORNECEDOR, CP.NUMERO_OC, CSC.CSC_DGCO, CSC.NUMERO_RC, OS.JUSTIFICATIVA, CP.CPF, CSC.CSC_CPF, CSC.FISICA_JUDIRICA, CP.SIM_NAO, P.NOME AS RESPONSAVEL, P.USUARIO_REDE AS USUARIO_RESPONSAVEL, CSP.SIGLA, CASE WHEN O.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - O.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - O.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(O.DATA_HORA_FIM_REAL - O.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((O.DATA_HORA_FIM_REAL - O.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO, UA.APROVADOR FROM OCORRENCIA O LEFT JOIN ORDEM_SERVICO OS ON O.ID_OCORRENCIA = OS.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO CP ON OS.ID_OCORRENCIA = CP.ID_OCORRENCIA LEFT JOIN CPE_CSC CSC ON O.ID_OCORRENCIA = CSC.ID_OCORRENCIA LEFT JOIN PESSOA P ON P.ID_PESSOA = O.ID_RESPONSAVEL LEFT JOIN CLASSE_SUB_PROCESSO CSP ON O.ID_CLASSE_SUB_PROC_INI = CSP.ID_CLASSE_SUB_PROCESSO LEFT JOIN AA_ULTIMO AAU ON AAU.ID_OCORRENCIA = O.ID_OCORRENCIA LEFT JOIN ULTIMO_APROVADOR UA ON UA.ID_OCORRENCIA = O.ID_OCORRENCIA WHERE (O.ID_CLASSE_SUB_PROC_INI IN (395) OR CSP.SIGLA IN ('REVISAOOC'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesOrdemCompra(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("WITH AA_ULTIMO AS (SELECT AA1.ID_OCORRENCIA, MAX(AA1.ID_ASSUNTO_APROVACAO) AS ID_ASSUNTO_APROVACAO FROM ASSUNTO_APROVACAO AA1 GROUP BY AA1.ID_OCORRENCIA), ULTIMO_APROVADOR AS (SELECT AAU.ID_OCORRENCIA, P.NOME AS APROVADOR FROM AA_ULTIMO AAU JOIN (SELECT A.ID_ASSUNTO_APROVACAO, A.ID_PESSOA, ROW_NUMBER() OVER (PARTITION BY A.ID_ASSUNTO_APROVACAO ORDER BY A.DATA_HORA_EVIDENCIA DESC) AS RN FROM APROVACAO A) A1 ON A1.ID_ASSUNTO_APROVACAO = AAU.ID_ASSUNTO_APROVACAO AND A1.RN = 1 JOIN PESSOA P ON P.ID_PESSOA = A1.ID_PESSOA) SELECT O.ASSUNTO, O.DATA_HORA_SOL, O.ID_CLASSE_SUB_PROC_INI, O.NUMERO, O.SITUACAO, O.DATA_HORA_ULT_ATUA, O.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, O.ID_OCORRENCIA, OS.DESCRICAO_DETALHADA, CP.CNPJ, CP.NOME_FORNECEDOR, CP.NUMERO_OC, CSC.CSC_DGCO, CSC.NUMERO_RC, OS.JUSTIFICATIVA, CP.CPF, CSC.CSC_CPF, CSC.FISICA_JUDIRICA, CP.SIM_NAO, P.NOME AS RESPONSAVEL, P.USUARIO_REDE AS USUARIO_RESPONSAVEL, CSP.SIGLA, CASE WHEN O.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - O.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - O.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(O.DATA_HORA_FIM_REAL - O.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((O.DATA_HORA_FIM_REAL - O.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO, UA.APROVADOR FROM OCORRENCIA O LEFT JOIN ORDEM_SERVICO OS ON O.ID_OCORRENCIA = OS.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO CP ON OS.ID_OCORRENCIA = CP.ID_OCORRENCIA LEFT JOIN CPE_CSC CSC ON O.ID_OCORRENCIA = CSC.ID_OCORRENCIA LEFT JOIN PESSOA P ON P.ID_PESSOA = O.ID_RESPONSAVEL LEFT JOIN CLASSE_SUB_PROCESSO CSP ON O.ID_CLASSE_SUB_PROC_INI = CSP.ID_CLASSE_SUB_PROCESSO LEFT JOIN AA_ULTIMO AAU ON AAU.ID_OCORRENCIA = O.ID_OCORRENCIA LEFT JOIN ULTIMO_APROVADOR UA ON UA.ID_OCORRENCIA = O.ID_OCORRENCIA WHERE (O.ID_CLASSE_SUB_PROC_INI IN (395) OR CSP.SIGLA IN ('REVISAOOC')) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



# P R O C E S S O S   A D M I N I S T R A T I V O S
def listarProcessosAdministrativos():
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.SITUACAO, OCORRENCIA.NUMERO, CPE_HOMOLOGACAO.TIP_SOLDR, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME AS RESPONSAVEL, PESSOA.USUARIO_REDE AS USUARIO_RESPONSAVEL, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CPE_CSC.CSC_DGCO, CLASSE_SUB_PROCESSO.SIGLA, CPE_CSC.CSC_DATA_FIM AS FIM_VIGENCIA, CPE_CSC.SIM_NAO1 AS COMISSAO, CPE_CSC.OBSERVACAO, CPE_CSC.OBJETO_CONTRATO, PESSOA1.NOME AS GESTOR, PESSOA2.NOME AS FISCAL_ADM, PESSOA3.NOME AS FISCAL_SERVICO, CASE WHEN OCORRENCIA.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO FROM OCORRENCIA LEFT JOIN CPE_CSC ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA LEFT JOIN CPE_HOMOLOGACAO ON OCORRENCIA.ID_OCORRENCIA = CPE_HOMOLOGACAO.ID_OCORRENCIA LEFT JOIN ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN PESSOA ON OCORRENCIA.ID_RESPONSAVEL = PESSOA.ID_PESSOA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CLASSE_SUB_PROCESSO ON OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO LEFT JOIN PESSOA PESSOA1 ON CPE_CSC.GESTOR_DO_CONTRATO = PESSOA1.ID_PESSOA LEFT JOIN PESSOA PESSOA2 ON CPE_CSC.FISCAL_ADM_DO_CONTRATO = PESSOA2.ID_PESSOA LEFT JOIN PESSOA PESSOA3 ON CPE_CSC.FISCAL_DE_SERVICO = PESSOA3.ID_PESSOA WHERE (OCORRENCIA.ID_CLASSE_SUB_PROC_INI IN (598) OR CLASSE_SUB_PROCESSO.SIGLA IN ('PROCESSADM'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesProcessoAdministrativo(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.SITUACAO, OCORRENCIA.NUMERO, CPE_HOMOLOGACAO.TIP_SOLDR, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME AS RESPONSAVEL, PESSOA.USUARIO_REDE AS USUARIO_RESPONSAVEL, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CPE_CSC.CSC_DGCO, CLASSE_SUB_PROCESSO.SIGLA, CPE_CSC.CSC_DATA_FIM AS FIM_VIGENCIA, CPE_CSC.SIM_NAO1 AS COMISSAO, CPE_CSC.OBSERVACAO, CPE_CSC.OBJETO_CONTRATO, PESSOA1.NOME AS GESTOR, PESSOA2.NOME AS FISCAL_ADM, PESSOA3.NOME AS FISCAL_SERVICO, CASE WHEN OCORRENCIA.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO FROM OCORRENCIA LEFT JOIN CPE_CSC ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA LEFT JOIN CPE_HOMOLOGACAO ON OCORRENCIA.ID_OCORRENCIA = CPE_HOMOLOGACAO.ID_OCORRENCIA LEFT JOIN ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN PESSOA ON OCORRENCIA.ID_RESPONSAVEL = PESSOA.ID_PESSOA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CLASSE_SUB_PROCESSO ON OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO LEFT JOIN PESSOA PESSOA1 ON CPE_CSC.GESTOR_DO_CONTRATO = PESSOA1.ID_PESSOA LEFT JOIN PESSOA PESSOA2 ON CPE_CSC.FISCAL_ADM_DO_CONTRATO = PESSOA2.ID_PESSOA LEFT JOIN PESSOA PESSOA3 ON CPE_CSC.FISCAL_DE_SERVICO = PESSOA3.ID_PESSOA WHERE (OCORRENCIA.ID_CLASSE_SUB_PROC_INI IN (598) OR CLASSE_SUB_PROCESSO.SIGLA IN ('PROCESSADM')) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



# D I S T R A T O S   E   R E S C I S Õ E S
def listarDistratosRescisoes():
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.SITUACAO, OCORRENCIA.NUMERO, CPE_CSC.NUMERO_DGCO, CPE_HOMOLOGACAO.TIP_SOLDR, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME AS RESPONSAVEL, PESSOA.USUARIO_REDE AS USUARIO_RESPONSAVEL, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CLASSE_SUB_PROCESSO.SIGLA, CPE_CSC.DEMANDANTE AS AREA_DEMANDANTE, CPE_CSC.CSC_EMPRESA, CP_ORDEM_SERVICO.RESUMO AS OBJETO, CP_ORDEM_SERVICO.DATA1 AS VIGENCIA_INICIAL, CP_ORDEM_SERVICO.DATA2 AS VIGENCIAL_FINAL, CP_ORDEM_SERVICO.MOTIVO AS DESCRICAI_ORRENCIA, PESSOA1.NOME AS FISCAL_SERVICO, PESSOA2.NOME AS GESTOR_CONTRATO, CPE_CSC.DESCRICAO_DETALHADA, CPE_CONTRATOS02.DATA_ASSINATURA_C, CPE_CONTRATOS02.DATA_ENCERRAMENTO_C, CASE WHEN OCORRENCIA.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO FROM OCORRENCIA LEFT JOIN CPE_CSC ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA LEFT JOIN CPE_HOMOLOGACAO ON OCORRENCIA.ID_OCORRENCIA = CPE_HOMOLOGACAO.ID_OCORRENCIA LEFT JOIN ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN PESSOA ON OCORRENCIA.ID_RESPONSAVEL = PESSOA.ID_PESSOA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CLASSE_SUB_PROCESSO ON OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO LEFT JOIN PESSOA PESSOA1 ON CPE_CSC.FISCAL_DE_SERVICO = PESSOA1.ID_PESSOA LEFT JOIN PESSOA PESSOA2 ON CPE_CSC.GESTOR_DO_CONTRATO = PESSOA2.ID_PESSOA LEFT JOIN CPE_CONTRATOS02 ON OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA WHERE OCORRENCIA.ID_OCORRENCIA > 1690000 AND (OCORRENCIA.ID_CLASSE_SUB_PROC_INI IN (659, 380) OR CLASSE_SUB_PROCESSO.SIGLA IN ('423', 'DISTRATOERESCI', 'DISTRATOERESCISAO'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesDistratoRescisao(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.SITUACAO, OCORRENCIA.NUMERO, CPE_CSC.NUMERO_DGCO, CPE_HOMOLOGACAO.TIP_SOLDR, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME AS RESPONSAVEL, PESSOA.USUARIO_REDE AS USUARIO_RESPONSAVEL, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CLASSE_SUB_PROCESSO.SIGLA, CPE_CSC.DEMANDANTE AS AREA_DEMANDANTE, CPE_CSC.CSC_EMPRESA, CP_ORDEM_SERVICO.RESUMO AS OBJETO, CP_ORDEM_SERVICO.DATA1 AS VIGENCIA_INICIAL, CP_ORDEM_SERVICO.DATA2 AS VIGENCIAL_FINAL, CP_ORDEM_SERVICO.MOTIVO AS DESCRICAI_ORRENCIA, PESSOA1.NOME AS FISCAL_SERVICO, PESSOA2.NOME AS GESTOR_CONTRATO, CPE_CSC.DESCRICAO_DETALHADA, CPE_CONTRATOS02.DATA_ASSINATURA_C, CPE_CONTRATOS02.DATA_ENCERRAMENTO_C, CASE WHEN OCORRENCIA.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO FROM OCORRENCIA LEFT JOIN CPE_CSC ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA LEFT JOIN CPE_HOMOLOGACAO ON OCORRENCIA.ID_OCORRENCIA = CPE_HOMOLOGACAO.ID_OCORRENCIA LEFT JOIN ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN PESSOA ON OCORRENCIA.ID_RESPONSAVEL = PESSOA.ID_PESSOA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CLASSE_SUB_PROCESSO ON OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO LEFT JOIN PESSOA PESSOA1 ON CPE_CSC.FISCAL_DE_SERVICO = PESSOA1.ID_PESSOA LEFT JOIN PESSOA PESSOA2 ON CPE_CSC.GESTOR_DO_CONTRATO = PESSOA2.ID_PESSOA LEFT JOIN CPE_CONTRATOS02 ON OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA WHERE OCORRENCIA.ID_OCORRENCIA > 1690000 AND (OCORRENCIA.ID_CLASSE_SUB_PROC_INI IN (659, 380) OR CLASSE_SUB_PROCESSO.SIGLA IN ('423', 'DISTRATOERESCI', 'DISTRATOERESCISAO')) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



# E N C E R R A M E N T O   C O N T R A T U A L
def listarEncerramentosContratuais():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_ULT_ATUA, CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CPE_CSC.OBJETO_CONTRATO, CPE_CSC.CSC_DATA_FIM, CPE_CSC.CSC_DGCO, CPE_CSC.OBSERVACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME As FISCAL_DE_SERVICO, PESSOA1.NOME As FISCAL_ADM_DO_CONTRATO, PESSOA2.NOME As GESTOR_DO_CONTRATO, OCORRENCIA.ID_OCORRENCIA, PESSOA3.NOME As RESPONSAVEL, PESSOA3.ID_PESSOA, PESSOA3.USUARIO_REDE As USUARIO_RESPONSAVEL, Case When OCORRENCIA.SITUACAO = 'Aberto' Then Floor(SysDate - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || Floor(Mod((SysDate - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' Else Floor(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || Floor(Mod((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' End As TEMPO, CPE_CSC.DATA_APROVACAO_FISCAL_ADM, CPE_CSC.DATA_APROVACAO_FISCAL_SERV, CPE_CSC.DATA_APROVACAO_GESTOR From OCORRENCIA Left Join CLASSE_SUB_PROCESSO On CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = OCORRENCIA.ID_CLASSE_SUB_PROC_INI Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = CPE_CSC.FISCAL_DE_SERVICO Left Join PESSOA PESSOA1 On PESSOA1.ID_PESSOA = CPE_CSC.FISCAL_ADM_DO_CONTRATO Left Join PESSOA PESSOA2 On PESSOA2.ID_PESSOA = CPE_CSC.GESTOR_DO_CONTRATO Left Join PESSOA PESSOA3 On PESSOA3.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Where (CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO In (536, 327) Or CLASSE_SUB_PROCESSO.SIGLA In ('AVSENCERRACONTRATO', 'AVISOENCERRACONT', 'ENCERRAMENTODECONTRATO'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesEncerramentoContratual(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_ULT_ATUA, CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CPE_CSC.OBJETO_CONTRATO, CPE_CSC.CSC_DATA_FIM, CPE_CSC.CSC_DGCO, CPE_CSC.OBSERVACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME As FISCAL_DE_SERVICO, PESSOA1.NOME As FISCAL_ADM_DO_CONTRATO, PESSOA2.NOME As GESTOR_DO_CONTRATO, OCORRENCIA.ID_OCORRENCIA, PESSOA3.NOME As RESPONSAVEL, PESSOA3.ID_PESSOA, PESSOA3.USUARIO_REDE As USUARIO_RESPONSAVEL, Case When OCORRENCIA.SITUACAO = 'Aberto' Then Floor(SysDate - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || Floor(Mod((SysDate - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' Else Floor(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || Floor(Mod((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' End As TEMPO, CPE_CSC.DATA_APROVACAO_FISCAL_ADM, CPE_CSC.DATA_APROVACAO_FISCAL_SERV, CPE_CSC.DATA_APROVACAO_GESTOR From OCORRENCIA Left Join CLASSE_SUB_PROCESSO On CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = OCORRENCIA.ID_CLASSE_SUB_PROC_INI Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = CPE_CSC.FISCAL_DE_SERVICO Left Join PESSOA PESSOA1 On PESSOA1.ID_PESSOA = CPE_CSC.FISCAL_ADM_DO_CONTRATO Left Join PESSOA PESSOA2 On PESSOA2.ID_PESSOA = CPE_CSC.GESTOR_DO_CONTRATO Left Join PESSOA PESSOA3 On PESSOA3.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Where (CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO In (536, 327) Or CLASSE_SUB_PROCESSO.SIGLA In ('AVSENCERRACONTRATO', 'AVISOENCERRACONT', 'ENCERRAMENTODECONTRATO')) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



# A T U A L I Z Ç Ã O   D E   D A D O S   B A N C Á R I O S
def listarAtualizacoesDeDadosBancarios():
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.SITUACAO, OCORRENCIA.NUMERO, OCORRENCIA.DATA_HORA_ULT_ATUA, CPE_CSC.BANCO_NOME, CPE_CSC.AGENCIA_NUMERO, CPE_CSC.CSC_DIGITO_AGENCIA, CPE_CSC.CONTA_CORRENTE_NUMERO, CPE_CSC.CSC_CPF, CPE_CONTRATOS.OBS2, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CP_ORDEM_SERVICO.CNPJ_FORNECEDOR, CPE_CONTRATOS.OBS3, PESSOA.NOME AS RESPONSAVEL, PESSOA.USUARIO_REDE AS USUARIO_RESPONSAVEL, CLASSE_SUB_PROCESSO.SIGLA, CASE WHEN OCORRENCIA.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO FROM OCORRENCIA LEFT JOIN CPE_CSC ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA LEFT JOIN CPE_CONTRATOS ON OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN PESSOA ON PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL LEFT JOIN CLASSE_SUB_PROCESSO ON OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO WHERE (OCORRENCIA.ID_CLASSE_SUB_PROC_INI IN (357) OR CLASSE_SUB_PROCESSO.SIGLA IN ('ALTERARDADOSBANCARIOS', 'AUTORIZARALTDADOSBANC'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesAtualizacaoDeDadosBancarios(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.SITUACAO, OCORRENCIA.NUMERO, OCORRENCIA.DATA_HORA_ULT_ATUA, CPE_CSC.BANCO_NOME, CPE_CSC.AGENCIA_NUMERO, CPE_CSC.CSC_DIGITO_AGENCIA, CPE_CSC.CONTA_CORRENTE_NUMERO, CPE_CSC.CSC_CPF, CPE_CONTRATOS.OBS2, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CP_ORDEM_SERVICO.CNPJ_FORNECEDOR, CPE_CONTRATOS.OBS3, PESSOA.NOME AS RESPONSAVEL, PESSOA.USUARIO_REDE AS USUARIO_RESPONSAVEL, CLASSE_SUB_PROCESSO.SIGLA, CASE WHEN OCORRENCIA.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO FROM OCORRENCIA LEFT JOIN CPE_CSC ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA LEFT JOIN CPE_CONTRATOS ON OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN PESSOA ON PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL LEFT JOIN CLASSE_SUB_PROCESSO ON OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO WHERE (OCORRENCIA.ID_CLASSE_SUB_PROC_INI IN (357) OR CLASSE_SUB_PROCESSO.SIGLA IN ('ALTERARDADOSBANCARIOS', 'AUTORIZARALTDADOSBANC')) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



# A T E S T A D O S   D E   C A P A C I D A D E   T É C N I C A
def listarAtestadosCapacidadeTecnica():
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, OCORRENCIA.DATA_HORA_ULT_ATUA, ORDEM_SERVICO.DESCRICAO_DETALHADA, OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, CPE_FINANCEIRO.DGCO_BB, CP_ORDEM_SERVICO.NOME_FORNECEDOR, PESSOA.NOME AS RESPONSAVEL, PESSOA.USUARIO_REDE AS USUARIO_RESPONSAVEL, CLASSE_SUB_PROCESSO.SIGLA, CASE WHEN OCORRENCIA.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO FROM OCORRENCIA LEFT JOIN ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CPE_FINANCEIRO ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN PESSOA ON PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL LEFT JOIN CLASSE_SUB_PROCESSO ON OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO WHERE (OCORRENCIA.ID_CLASSE_SUB_PROC_INI IN (348) OR CLASSE_SUB_PROCESSO.SIGLA IN ('EMISSAOATESTADOFORNECEDOR', 'ATESTADOCAPTECFORNECEDOR'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesAtestadosDeCapacidadeTecnica(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, OCORRENCIA.DATA_HORA_ULT_ATUA, ORDEM_SERVICO.DESCRICAO_DETALHADA, OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, CPE_FINANCEIRO.DGCO_BB, CP_ORDEM_SERVICO.NOME_FORNECEDOR, PESSOA.NOME AS RESPONSAVEL, PESSOA.USUARIO_REDE AS USUARIO_RESPONSAVEL, CLASSE_SUB_PROCESSO.SIGLA, CASE WHEN OCORRENCIA.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO FROM OCORRENCIA LEFT JOIN ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CPE_FINANCEIRO ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN PESSOA ON PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL LEFT JOIN CLASSE_SUB_PROCESSO ON OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO WHERE (OCORRENCIA.ID_CLASSE_SUB_PROC_INI IN (348) OR CLASSE_SUB_PROCESSO.SIGLA IN ('EMISSAOATESTADOFORNECEDOR', 'ATESTADOCAPTECFORNECEDOR')) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



# T E R M O S   D E S I G N A Ç Ã O
def buscarChamadosTermo():
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.ID_OCORRENCIA AS IDENTIFICADOR, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, CPE_FINANCEIRO1.DGCO_BB AS DGCO, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO, CPE_CONTRATOS02.TIPO_DESIGNACAO_INTERV, CPE_CONTRATOS02.DESIGNA_TITU_OR_SUP, PESSOA.NOME AS DESIGNADO, CLASSE_SUB_PROCESSO.SIGLA, CASE WHEN OCORRENCIA.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO FROM OCORRENCIA LEFT JOIN CPE_FINANCEIRO ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CPE_FINANCEIRO CPE_FINANCEIRO1 ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA LEFT JOIN CPE_CONTRATOS02 ON OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA LEFT JOIN CLASSE_SUB_PROCESSO ON OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO LEFT JOIN PESSOA ON PESSOA.ID_PESSOA = CASE WHEN REGEXP_LIKE(CP_ORDEM_SERVICO.FAVORECIDO_ALL, '^[0-9]+$') THEN TO_NUMBER(CP_ORDEM_SERVICO.FAVORECIDO_ALL) ELSE NULL END WHERE (OCORRENCIA.ID_CLASSE_SUB_PROC_INI IN (658, 637) OR CLASSE_SUB_PROCESSO.SIGLA IN ('TERMOACEITEDESIGNACAOO', 'TERMOINTERVCONTRAT', 'TERMODEDESIGNACAO'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarTermosPorOs(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.ID_OCORRENCIA AS IDENTIFICADOR, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, CPE_FINANCEIRO1.DGCO_BB AS DGCO, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO, CPE_CONTRATOS02.TIPO_DESIGNACAO_INTERV, CPE_CONTRATOS02.DESIGNA_TITU_OR_SUP, PESSOA.NOME AS DESIGNADO, CLASSE_SUB_PROCESSO.SIGLA, CASE WHEN OCORRENCIA.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO FROM OCORRENCIA LEFT JOIN CPE_FINANCEIRO ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CPE_FINANCEIRO CPE_FINANCEIRO1 ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA LEFT JOIN CPE_CONTRATOS02 ON OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA LEFT JOIN CLASSE_SUB_PROCESSO ON OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO LEFT JOIN PESSOA ON PESSOA.ID_PESSOA = CASE WHEN REGEXP_LIKE(CP_ORDEM_SERVICO.FAVORECIDO_ALL, '^[0-9]+$') THEN TO_NUMBER(CP_ORDEM_SERVICO.FAVORECIDO_ALL) ELSE NULL END WHERE (OCORRENCIA.ID_CLASSE_SUB_PROC_INI IN (658, 637) OR CLASSE_SUB_PROCESSO.SIGLA IN ('TERMOACEITEDESIGNACAOO', 'TERMOINTERVCONTRAT', 'TERMODEDESIGNACAO')) AND OCORRENCIA.NUMERO LIKE '%{}%'".format(numeroOs))
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesTermo(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.ID_OCORRENCIA AS IDENTIFICADOR, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, CPE_FINANCEIRO1.DGCO_BB AS DGCO, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO, CPE_CONTRATOS02.TIPO_DESIGNACAO_INTERV, CPE_CONTRATOS02.DESIGNA_TITU_OR_SUP, PESSOA.NOME AS DESIGNADO, CLASSE_SUB_PROCESSO.SIGLA, CASE WHEN OCORRENCIA.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO FROM OCORRENCIA LEFT JOIN CPE_FINANCEIRO ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CPE_FINANCEIRO CPE_FINANCEIRO1 ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA LEFT JOIN CPE_CONTRATOS02 ON OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA LEFT JOIN CLASSE_SUB_PROCESSO ON OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO LEFT JOIN PESSOA ON PESSOA.ID_PESSOA = CASE WHEN REGEXP_LIKE(CP_ORDEM_SERVICO.FAVORECIDO_ALL, '^[0-9]+$') THEN TO_NUMBER(CP_ORDEM_SERVICO.FAVORECIDO_ALL) ELSE NULL END WHERE (OCORRENCIA.ID_CLASSE_SUB_PROC_INI IN (658, 637) OR CLASSE_SUB_PROCESSO.SIGLA IN ('TERMOACEITEDESIGNACAOO', 'TERMOINTERVCONTRAT', 'TERMODEDESIGNACAO')) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



# D E S I G N A Ç Ã O
def buscarChamadosDesignacao():
    try:
        result_table2 = DB.ExecuteDataTable("WITH ULTIMO_AA AS (SELECT AA.ID_OCORRENCIA, AA.ID_ASSUNTO_APROVACAO, ROW_NUMBER() OVER (PARTITION BY AA.ID_OCORRENCIA ORDER BY AA.ID_ASSUNTO_APROVACAO DESC) AS RN FROM ASSUNTO_APROVACAO AA), ULTIMO_APROV AS (SELECT UA.ID_OCORRENCIA, A.ID_PESSOA, ROW_NUMBER() OVER (PARTITION BY UA.ID_OCORRENCIA ORDER BY A.DATA_HORA_EVIDENCIA DESC) AS RN FROM ULTIMO_AA UA JOIN APROVACAO A ON A.ID_ASSUNTO_APROVACAO = UA.ID_ASSUNTO_APROVACAO WHERE UA.RN = 1), APROVADOR_POR_OCORRENCIA AS (SELECT U.ID_OCORRENCIA, P2.NOME AS APROVADOR FROM ULTIMO_APROV U JOIN PESSOA P2 ON P2.ID_PESSOA = U.ID_PESSOA WHERE U.RN = 1), OS_AGR AS (SELECT ID_OCORRENCIA, MIN(NOME_FORNECEDOR) AS NOME_FORNECEDOR, MIN(OBJETO_CONTRATACAO) AS OBJETO_CONTRATACAO FROM CP_ORDEM_SERVICO GROUP BY ID_OCORRENCIA), FIN_AGR AS (SELECT ID_OCORRENCIA, MIN(DGCO_BB) AS DGCO_BB FROM CPE_FINANCEIRO GROUP BY ID_OCORRENCIA), CTRT_AGR AS (SELECT ID_OCORRENCIA, MIN(COMBOBOX_6) AS TIPO_DESIGNACAO FROM CPE_CONTRATOS GROUP BY ID_OCORRENCIA) SELECT O.ID_OCORRENCIA AS IDENTIFICADOR, O.ID_CLASSE_SUB_PROC_INI, O.DATA_HORA_ULT_ATUA, O.DATA_HORA_SOL, O.ASSUNTO, O.DATA_HORA_SOL, O.NUMERO, O.SITUACAO, OS.NOME_FORNECEDOR, O.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, FIN.DGCO_BB AS DGCO, OS.OBJETO_CONTRATACAO, CTRT.TIPO_DESIGNACAO, CSP.SIGLA, P.NOME AS SOLICITANTE, P1.NOME AS RESPONSAVEL, (SELECT RTRIM(XMLAGG(XMLELEMENT(e, DGCO || '; ').EXTRACT('//text()') ORDER BY DGCO).GetClobVal(), '; ') FROM Z_00143_GRID_DESIGNACAO WHERE ID_OCORRENCIA = O.ID_OCORRENCIA) AS DGCO_LISTA, (SELECT RTRIM(XMLAGG(XMLELEMENT(e, SUBSTR(RAZAO_SOCIAL, 1, 59) || '; ').EXTRACT('//text()') ORDER BY RAZAO_SOCIAL).GetClobVal(), '; ') FROM Z_00143_GRID_DESIGNACAO WHERE ID_OCORRENCIA = O.ID_OCORRENCIA) AS RAZAO_SOCIAL_LISTA, CASE WHEN O.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - O.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - O.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(O.DATA_HORA_FIM_REAL - O.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((O.DATA_HORA_FIM_REAL - O.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO, AP.APROVADOR FROM OCORRENCIA O LEFT JOIN OS_AGR OS ON OS.ID_OCORRENCIA = O.ID_OCORRENCIA LEFT JOIN FIN_AGR FIN ON FIN.ID_OCORRENCIA = O.ID_OCORRENCIA LEFT JOIN CTRT_AGR CTRT ON CTRT.ID_OCORRENCIA = O.ID_OCORRENCIA LEFT JOIN CLASSE_SUB_PROCESSO CSP ON O.ID_CLASSE_SUB_PROC_INI = CSP.ID_CLASSE_SUB_PROCESSO LEFT JOIN PESSOA P ON O.ID_CLIENTE = P.ID_PESSOA LEFT JOIN PESSOA P1 ON O.ID_RESPONSAVEL = P1.ID_PESSOA LEFT JOIN APROVADOR_POR_OCORRENCIA AP ON AP.ID_OCORRENCIA = O.ID_OCORRENCIA WHERE (O.ID_CLASSE_SUB_PROC_INI IN (654, 635)) OR (CSP.SIGLA IN ('DESIGNACAOSISCONNN', 'DESIGNASISCCON2', 'DESIGNACAODEINTERVENIENTES'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesDesignacao(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.ID_OCORRENCIA AS IDENTIFICADOR, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, CPE_FINANCEIRO1.DGCO_BB AS DGCO, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO, CPE_CONTRATOS.COMBOBOX_6 AS tipo_designacao, CLASSE_SUB_PROCESSO.SIGLA, PESSOA.NOME AS SOLICITANTE, PESSOA1.NOME AS RESPONSAVEL, LISTAGG(Z_00143_GRID_DESIGNACAO.DGCO, '; ') WITHIN GROUP (ORDER BY Z_00143_GRID_DESIGNACAO.DGCO) AS DGCO_LISTA, LISTAGG(SUBSTR(Z_00143_GRID_DESIGNACAO.RAZAO_SOCIAL, 1, 59), '; ') WITHIN GROUP (ORDER BY Z_00143_GRID_DESIGNACAO.RAZAO_SOCIAL) AS RAZAO_SOCIAL_LISTA, CASE WHEN OCORRENCIA.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO, (SELECT versao FROM (SELECT VA.VERSAO AS versao FROM VERSAO_APROVACAO VA WHERE VA.ID_ASSUNTO_APROVACAO = ASSUNTO_APROVACAO.ID_ASSUNTO_APROVACAO ORDER BY VA.DATA_HORA_CRIACAO DESC) WHERE ROWNUM = 1) AS VERSAO_APROVACAO, ASSUNTO_APROVACAO.ID_ASSUNTO_APROVACAO, (SELECT situacao FROM (SELECT A.SITUACAO AS situacao FROM APROVACAO A WHERE A.ID_ASSUNTO_APROVACAO = ASSUNTO_APROVACAO.ID_ASSUNTO_APROVACAO ORDER BY A.DATA_HORA_EVIDENCIA DESC) WHERE ROWNUM = 1) AS SITUACAO_APROVACAO, (SELECT situacao FROM (SELECT VA.SITUACAO AS situacao FROM VERSAO_APROVACAO VA WHERE VA.ID_ASSUNTO_APROVACAO = ASSUNTO_APROVACAO.ID_ASSUNTO_APROVACAO ORDER BY VA.DATA_HORA_CRIACAO DESC) WHERE ROWNUM = 1) AS SITUACAO_VERSAO_APROVACAO, (SELECT motivo FROM (SELECT A.MOTIVO AS motivo FROM APROVACAO A WHERE A.ID_ASSUNTO_APROVACAO = ASSUNTO_APROVACAO.ID_ASSUNTO_APROVACAO ORDER BY A.DATA_HORA_EVIDENCIA DESC) WHERE ROWNUM = 1) AS MOTIVO_APROVACAO, (SELECT data_criacao FROM (SELECT VA.DATA_HORA_CRIACAO AS data_criacao FROM VERSAO_APROVACAO VA WHERE VA.ID_ASSUNTO_APROVACAO = ASSUNTO_APROVACAO.ID_ASSUNTO_APROVACAO ORDER BY VA.DATA_HORA_CRIACAO DESC) WHERE ROWNUM = 1) AS DATA_HORA_CRIACAO_VERSAO, (SELECT nome_aprovador FROM (SELECT P2.NOME AS nome_aprovador FROM APROVACAO A JOIN PESSOA P2 ON A.ID_PESSOA = P2.ID_PESSOA WHERE A.ID_ASSUNTO_APROVACAO = ASSUNTO_APROVACAO.ID_ASSUNTO_APROVACAO ORDER BY A.DATA_HORA_EVIDENCIA DESC) WHERE ROWNUM = 1) AS APROVADOR FROM OCORRENCIA LEFT JOIN CPE_FINANCEIRO ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CPE_FINANCEIRO CPE_FINANCEIRO1 ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA LEFT JOIN CLASSE_SUB_PROCESSO ON OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO LEFT JOIN CPE_CONTRATOS ON OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS.ID_OCORRENCIA LEFT JOIN PESSOA ON OCORRENCIA.ID_CLIENTE = PESSOA.ID_PESSOA LEFT JOIN PESSOA PESSOA1 ON OCORRENCIA.ID_RESPONSAVEL = PESSOA1.ID_PESSOA LEFT JOIN Z_00143_GRID_DESIGNACAO ON OCORRENCIA.ID_OCORRENCIA = Z_00143_GRID_DESIGNACAO.ID_OCORRENCIA LEFT JOIN ASSUNTO_APROVACAO ON OCORRENCIA.ID_OCORRENCIA = ASSUNTO_APROVACAO.ID_OCORRENCIA WHERE (OCORRENCIA.ID_CLASSE_SUB_PROC_INI IN (654, 635) OR CLASSE_SUB_PROCESSO.SIGLA IN ('DESIGNACAOSISCONNN', 'DESIGNASISCCON2', 'DESIGNACAODEINTERVENIENTES')) AND OCORRENCIA.NUMERO = '"+str(numeroOs)+"' GROUP BY OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, OCORRENCIA.DATA_HORA_FIM_REAL, CPE_FINANCEIRO1.DGCO_BB, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO, CPE_CONTRATOS.COMBOBOX_6, CLASSE_SUB_PROCESSO.SIGLA, PESSOA.NOME, PESSOA1.NOME, ASSUNTO_APROVACAO.ID_ASSUNTO_APROVACAO")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)

        
# A V A L I A Ç Ã O
def buscarChamadosAvaliacao():
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.ID_OCORRENCIA AS IDENTIFICADOR, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CPE_CSC.COLABORADOR AS AVALIADOR, CPE_CONTRATOS02.NOTA_AVALIACAO AS MEDIA_TRIMESTRAL, CPE_HOMOLOGACAO.DIAS AS ANO, CP_ORDEM_SERVICO.DIAS_PRAZO AS PERIODO, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, CPE_CONTRATOS02.COLABORADOR2 AS GESTOR, CPE_CSC1.CSC_DGCO, CPE_CONTRATOS02.NM_GERENCIA AS GERENCIA, CLASSE_SUB_PROCESSO.SIGLA, CPE_CONTRATOS02.TIPO_AVALIACAO, CASE WHEN OCORRENCIA.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO FROM OCORRENCIA LEFT JOIN CPE_FINANCEIRO ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CPE_CSC ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA LEFT JOIN CPE_CONTRATOS02 ON OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA LEFT JOIN CPE_HOMOLOGACAO ON OCORRENCIA.ID_OCORRENCIA = CPE_HOMOLOGACAO.ID_OCORRENCIA LEFT JOIN CLASSE_SUB_PROCESSO ON OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO LEFT JOIN CPE_CSC CPE_CSC1 ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC1.ID_OCORRENCIA WHERE (OCORRENCIA.ID_CLASSE_SUB_PROC_INI IN (641, 655) OR CLASSE_SUB_PROCESSO.SIGLA IN ('AVALIAFISCASERVICOOO', 'AVFOR', 'AVALIFORNECEDORES'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesAvaliacao(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.ID_OCORRENCIA AS IDENTIFICADOR, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CPE_CSC.COLABORADOR AS AVALIADOR, CPE_CONTRATOS02.NOTA_AVALIACAO AS MEDIA_TRIMESTRAL, CPE_HOMOLOGACAO.DIAS AS ANO, CP_ORDEM_SERVICO.DIAS_PRAZO AS PERIODO, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, CPE_CONTRATOS02.COLABORADOR2 AS GESTOR, CPE_CSC1.CSC_DGCO, CPE_CONTRATOS02.NM_GERENCIA AS GERENCIA, CLASSE_SUB_PROCESSO.SIGLA, CPE_CONTRATOS02.TIPO_AVALIACAO, CASE WHEN OCORRENCIA.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO FROM OCORRENCIA LEFT JOIN CPE_FINANCEIRO ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CPE_CSC ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA LEFT JOIN CPE_CONTRATOS02 ON OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA LEFT JOIN CPE_HOMOLOGACAO ON OCORRENCIA.ID_OCORRENCIA = CPE_HOMOLOGACAO.ID_OCORRENCIA LEFT JOIN CLASSE_SUB_PROCESSO ON OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO LEFT JOIN CPE_CSC CPE_CSC1 ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC1.ID_OCORRENCIA WHERE (OCORRENCIA.ID_CLASSE_SUB_PROC_INI IN (641, 655) OR CLASSE_SUB_PROCESSO.SIGLA IN ('AVALIAFISCASERVICOOO', 'AVFOR', 'AVALIFORNECEDORES')) AND OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)

# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# OLD STUFFS




# ONBOARD
def listarOnBoard():
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, CP_ORDEM_SERVICO.NOME_FORNECEDOR, NVL(CPE_FINANCEIRO.DGCO_BB, CPE_CSC.CSC_DGCO) AS CSC_DGCO, PESSOA.NOME AS RESPONSAVEL, PESSOA.USUARIO_REDE AS USUARIO_RESPONSAVEL, CPE_CSC.SIM_NAO3 AS COMISSAO, CPE_CSC.OBS21 AS OBJETO, PESSOA1.NOME AS ANALISTA_TITULAR, CPE_CONTRATOS02.MATRICULA_ANA_TITU AS MATRICULA_TITULAR, PESSOA2.NOME AS ANALISTA_SUPLENTE, CPE_CONTRATOS02.MATRICULA_ANA_SUP AS MATRICULA_SUPLENTE, CLASSE_SUB_PROCESSO.SIGLA, CASE WHEN OCORRENCIA.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO FROM OCORRENCIA LEFT JOIN ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON ORDEM_SERVICO.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CPE_CSC ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA LEFT JOIN PESSOA ON PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL LEFT JOIN CPE_FINANCEIRO ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA LEFT JOIN CPE_CONTRATOS02 ON OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA LEFT JOIN PESSOA PESSOA1 ON PESSOA1.ID_PESSOA = CPE_CONTRATOS02.ANALISTA_CONTRATO_TITU LEFT JOIN CLASSE_SUB_PROCESSO ON OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO LEFT JOIN PESSOA PESSOA2 ON PESSOA2.ID_PESSOA = CPE_CONTRATOS02.ANALISTA_CONTRATO_SUP WHERE (OCORRENCIA.ID_CLASSE_SUB_PROC_INI IN (625) OR CLASSE_SUB_PROCESSO.SIGLA IN ('ONBOARD'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesOnBoard(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, CP_ORDEM_SERVICO.NOME_FORNECEDOR, NVL(CPE_FINANCEIRO.DGCO_BB, CPE_CSC.CSC_DGCO) AS CSC_DGCO, PESSOA.NOME AS RESPONSAVEL, PESSOA.USUARIO_REDE AS USUARIO_RESPONSAVEL, CPE_CSC.SIM_NAO3 AS COMISSAO, CPE_CSC.OBS21 AS OBJETO, PESSOA1.NOME AS ANALISTA_TITULAR, CPE_CONTRATOS02.MATRICULA_ANA_TITU AS MATRICULA_TITULAR, PESSOA2.NOME AS ANALISTA_SUPLENTE, CPE_CONTRATOS02.MATRICULA_ANA_SUP AS MATRICULA_SUPLENTE, CLASSE_SUB_PROCESSO.SIGLA, CASE WHEN OCORRENCIA.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO FROM OCORRENCIA LEFT JOIN ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON ORDEM_SERVICO.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CPE_CSC ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA LEFT JOIN PESSOA ON PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL LEFT JOIN CPE_FINANCEIRO ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA LEFT JOIN CPE_CONTRATOS02 ON OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA LEFT JOIN PESSOA PESSOA1 ON PESSOA1.ID_PESSOA = CPE_CONTRATOS02.ANALISTA_CONTRATO_TITU LEFT JOIN CLASSE_SUB_PROCESSO ON OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO LEFT JOIN PESSOA PESSOA2 ON PESSOA2.ID_PESSOA = CPE_CONTRATOS02.ANALISTA_CONTRATO_SUP WHERE (OCORRENCIA.ID_CLASSE_SUB_PROC_INI IN (625) OR CLASSE_SUB_PROCESSO.SIGLA IN ('ONBOARD')) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)




# GARANTIA
def listarGarantia():
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.NUMERO, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, OCORRENCIA.SITUACAO, OCORRENCIA.ID_OCORRENCIA, NVL(CPE_FINANCEIRO.DGCO_BB, CPE_CSC.CSC_DGCO) AS CSC_DGCO, PESSOA.NOME AS RESPONSAVEL, PESSOA.USUARIO_REDE AS USUARIO_RESPONSAVEL, CP_ORDEM_SERVICO.SIM_NAO AS POSSUI_GARANTIA, CLASSE_SUB_PROCESSO.SIGLA, CASE WHEN OCORRENCIA.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO FROM OCORRENCIA LEFT JOIN ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON ORDEM_SERVICO.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CPE_CSC ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA LEFT JOIN PESSOA ON PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL LEFT JOIN CPE_FINANCEIRO ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA LEFT JOIN CPE_CONTRATOS02 ON OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA LEFT JOIN PESSOA PESSOA1 ON PESSOA1.ID_PESSOA = CPE_CONTRATOS02.ANALISTA_CONTRATO_TITU LEFT JOIN PESSOA PESSOA2 ON PESSOA2.ID_PESSOA = CPE_CONTRATOS02.ANALISTA_CONTRATO_SUP LEFT JOIN CLASSE_SUB_PROCESSO ON OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO WHERE (OCORRENCIA.ID_CLASSE_SUB_PROC_INI IN (404) OR CLASSE_SUB_PROCESSO.SIGLA IN ('ANGACOL', 'ANAGARANCONT'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesGarantia(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.NUMERO, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, OCORRENCIA.SITUACAO, OCORRENCIA.ID_OCORRENCIA, NVL(CPE_FINANCEIRO.DGCO_BB, CPE_CSC.CSC_DGCO) AS CSC_DGCO, PESSOA.NOME AS RESPONSAVEL, PESSOA.USUARIO_REDE AS USUARIO_RESPONSAVEL, CP_ORDEM_SERVICO.SIM_NAO AS POSSUI_GARANTIA, CLASSE_SUB_PROCESSO.SIGLA, CASE WHEN OCORRENCIA.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO FROM OCORRENCIA LEFT JOIN ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON ORDEM_SERVICO.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CPE_CSC ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA LEFT JOIN PESSOA ON PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL LEFT JOIN CPE_FINANCEIRO ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA LEFT JOIN CPE_CONTRATOS02 ON OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA LEFT JOIN PESSOA PESSOA1 ON PESSOA1.ID_PESSOA = CPE_CONTRATOS02.ANALISTA_CONTRATO_TITU LEFT JOIN PESSOA PESSOA2 ON PESSOA2.ID_PESSOA = CPE_CONTRATOS02.ANALISTA_CONTRATO_SUP LEFT JOIN CLASSE_SUB_PROCESSO ON OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO WHERE (OCORRENCIA.ID_CLASSE_SUB_PROC_INI IN (404) OR CLASSE_SUB_PROCESSO.SIGLA IN ('ANGACOL', 'ANAGARANCONT')) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e) 



        
        
        
# CHAMADÃO
def listarInserirDocumentosContratuais():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.NUMERO As NUMERO, OCORRENCIA.SITUACAO As SITUACAO, OCORRENCIA.ASSUNTO As ASSUNTO, OCORRENCIA.DATA_HORA_SOL As DATA_HORA_SOL, OCORRENCIA.DATA_HORA_ULT_ATUA As DATA_HORA_ULT_ATUA, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, PESSOA.NOME As RESPONSAVEL, PESSOA_CLIENTE.NOME As CLIENTE, CPE_FINANCEIRO.DGCO_BB As CSC_DGCO, CP_ORDEM_SERVICO.NOME_FORNECEDOR As NOME_FORNECEDOR, Case When OCORRENCIA.SITUACAO = 'Aberto' Then Floor(SysDate - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || Floor(Mod((SysDate - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' Else Floor(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || Floor(Mod((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' End As TEMPO, PESSOA_AREA_DEMANDANTE.NOME As RESPONSAVEL_AREA_DEMANDANTE, CP_ORDEM_SERVICO.SCR_TODOS_RH As AREA_CONTRATO, CPE_CSC.DIRETORIA_GERENCIA As DIRETORIA_GERENCIA, CPE_CSC.CSC_DATA_INICIO As INICIO_VIGENCIA, CPE_CSC.CSC_DATA_FIM As FIM_VIGENCIA, OCORRENCIA.ID_CLASSE_SUB_PROC_INI As IDENTIFICADOR, COALESCE(CAST(CPE_CSC.OBJETO_CONTRATO AS VARCHAR2(4000)), CAST(CPE_CSC.OBS21 AS VARCHAR2(4000)) ) AS OBJETO From OCORRENCIA Left Join CLASSE_SUB_PROCESSO On CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = OCORRENCIA.ID_CLASSE_SUB_PROC_INI Left Join ORDEM_SERVICO On ORDEM_SERVICO.ID_OCORRENCIA = OCORRENCIA.ID_OCORRENCIA Left Join PESSOA On OCORRENCIA.ID_RESPONSAVEL = PESSOA.ID_PESSOA Left Join PESSOA PESSOA_CLIENTE On OCORRENCIA.ID_CLIENTE = PESSOA_CLIENTE.ID_PESSOA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA PESSOA_AREA_DEMANDANTE On CP_ORDEM_SERVICO.FAVORECIDO_TODOS = PESSOA_AREA_DEMANDANTE.ID_PESSOA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Where (CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO In (346)) Or (CLASSE_SUB_PROCESSO.SIGLA In ('INSERIRDOCSGESCON')) Order By OCORRENCIA.DATA_HORA_SOL")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesInserirDocumentosContratuais(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.NUMERO As NUMERO, OCORRENCIA.SITUACAO As SITUACAO, OCORRENCIA.ASSUNTO As ASSUNTO, OCORRENCIA.DATA_HORA_SOL As DATA_HORA_SOL, OCORRENCIA.DATA_HORA_ULT_ATUA As DATA_HORA_ULT_ATUA, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, PESSOA.NOME As RESPONSAVEL, PESSOA_CLIENTE.NOME As CLIENTE, CPE_FINANCEIRO.DGCO_BB As CSC_DGCO, CP_ORDEM_SERVICO.NOME_FORNECEDOR As NOME_FORNECEDOR, Case When OCORRENCIA.SITUACAO = 'Aberto' Then Floor(SysDate - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || Floor(Mod((SysDate - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' Else Floor(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || Floor(Mod((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' End As TEMPO, PESSOA_AREA_DEMANDANTE.NOME As RESPONSAVEL_AREA_DEMANDANTE, CP_ORDEM_SERVICO.SCR_TODOS_RH As AREA_CONTRATO, CPE_CSC.DIRETORIA_GERENCIA As DIRETORIA_GERENCIA, CPE_CSC.CSC_DATA_INICIO As INICIO_VIGENCIA, CPE_CSC.CSC_DATA_FIM As FIM_VIGENCIA, OCORRENCIA.ID_CLASSE_SUB_PROC_INI As IDENTIFICADOR, COALESCE(CAST(CPE_CSC.OBJETO_CONTRATO AS VARCHAR2(4000)), CAST(CPE_CSC.OBS21 AS VARCHAR2(4000)) ) AS OBJETO From OCORRENCIA Left Join CLASSE_SUB_PROCESSO On CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = OCORRENCIA.ID_CLASSE_SUB_PROC_INI Left Join ORDEM_SERVICO On ORDEM_SERVICO.ID_OCORRENCIA = OCORRENCIA.ID_OCORRENCIA Left Join PESSOA On OCORRENCIA.ID_RESPONSAVEL = PESSOA.ID_PESSOA Left Join PESSOA PESSOA_CLIENTE On OCORRENCIA.ID_CLIENTE = PESSOA_CLIENTE.ID_PESSOA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA PESSOA_AREA_DEMANDANTE On CP_ORDEM_SERVICO.FAVORECIDO_TODOS = PESSOA_AREA_DEMANDANTE.ID_PESSOA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Where (CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO In (346) Or CLASSE_SUB_PROCESSO.SIGLA In ('INSERIRDOCSGESCON')) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)
        
        
        
def buscarOCInserirDocumentosContratuaisPorOs(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select Unique CLASSE_SUB_PROCESSO.DESCRICAO, CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO, CLASSE_SUB_PROCESSO.SIGLA, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, CPE_FINANCEIRO.DGCO_BB As CSC_DGCO, CP_ORDEM_SERVICO.NUMERO_OC, CPE_CSC.NUMERO_RC, CPE_CSC.TIPO_SOLICITACAO_OC As TIPO_SOLICITACAO_OC, CPE_CSC.TIPO_OC_CSC As TIPO_OC, CPE_CONTRATOS.MODALIDADE_DE_CONTRATACAO, CPE_CONTRATOS.OBS5 As DESCRICAO_DETALHADA, PESSOA.NOME As RESPONSAVEL_TRATAMENTO, OCORRENCIA.SITUACAO, OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL As DATA_HORA_SOL, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, Case When OCORRENCIA.SITUACAO = 'Aberto' Then Floor(SysDate - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || Floor(Mod((SysDate - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' Else Floor(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || Floor(Mod((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' End As TEMPO From OCORRENCIA Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_CONTRATOS On OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = CP_ORDEM_SERVICO.FAVORECIDO_TODOS Where (CLASSE_SUB_PROCESSO.SIGLA In ('ORDEMDECOMRAS') Or OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (130)) AND OCORRENCIA.NUMERO LIKE '%{}%'".format(numeroOs))
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)
        
        
        
        
        
def buscarFiscoTributaInserirDocumentosContratuaisPorOs(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select Unique CLASSE_SUB_PROCESSO.DESCRICAO, CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO, CLASSE_SUB_PROCESSO.SIGLA, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, OCORRENCIA.SITUACAO, OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL As DATA_HORA_SOL, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, Case When OCORRENCIA.SITUACAO = 'Aberto' Then Floor(SysDate - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || Floor(Mod((SysDate - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' Else Floor(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || Floor(Mod((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' End As TEMPO, PESSOA.NOME As RESPONSAVEL From OCORRENCIA Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Inner Join PESSOA On OCORRENCIA.ID_RESPONSAVEL = PESSOA.ID_PESSOA Where (CLASSE_SUB_PROCESSO.SIGLA In ('CONFISCOTRIBUTARIA') Or OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (71)) AND OCORRENCIA.NUMERO LIKE '%{}%'".format(numeroOs))
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


        
        
        
def enviaDadosGestoresUor():
    try:
        result_table2 = DB.ExecuteDataTable("SELECT MAX(matricula_sup_nivel1) AS MATRICULA_GESTOR, f.numero_subcr_nivel1 AS NUMERO, MAX(f.descricao_subcr_nivel1) AS DESCRICAO, MAX(c.scr_sigla) AS SIGLA FROM CAD_FUNCIONARIO_V F Left Join cob_gl_centro c ON c.scr = f.numero_subcr_nivel1 WHERE f.matricula_sup_nivel1 != ' ' GROUP BY f.numero_subcr_nivel1")
        
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)




def enviaDadosAnalisePB(matriculaCondutor, situacao):
    try:
        if matriculaCondutor != "0":
            if situacao == "todos":
                result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ASSUNTO, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME, CP_PESSOA.MATRICULA From OCORRENCIA Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_CLIENTE Left Join CP_PESSOA On PESSOA.ID_PESSOA = CP_PESSOA.ID_PESSOA Where CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = 425 And CP_PESSOA.MATRICULA = '"+matriculaCondutor+"' Order By OCORRENCIA.NUMERO")
            else:
                result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ASSUNTO, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME, CP_PESSOA.MATRICULA From OCORRENCIA Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_CLIENTE Left Join CP_PESSOA On PESSOA.ID_PESSOA = CP_PESSOA.ID_PESSOA Where CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = 425 And CP_PESSOA.MATRICULA = '"+matriculaCondutor+"' And OCORRENCIA.SITUACAO = '"+situacao+"' Order By OCORRENCIA.NUMERO")    
        else:
            if situacao == "todos":
                result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ASSUNTO, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME, CP_PESSOA.MATRICULA From OCORRENCIA Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_CLIENTE Left Join CP_PESSOA On PESSOA.ID_PESSOA = CP_PESSOA.ID_PESSOA Where CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = 425 Order By OCORRENCIA.NUMERO")
            else:
                result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ASSUNTO, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME, CP_PESSOA.MATRICULA From OCORRENCIA Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_CLIENTE Left Join CP_PESSOA On PESSOA.ID_PESSOA = CP_PESSOA.ID_PESSOA Where CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = 425 And OCORRENCIA.SITUACAO = '"+situacao+"' Order By OCORRENCIA.NUMERO")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



def enviaDadosContratacao():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.SITUACAO, OCORRENCIA.NUMERO, ORDEM_SERVICO.DESCRICAO_DETALHADA As OBJETO_CONTRATACAO, PESSOA.NOME As RESPONSAVEL, PESSOA.USUARIO_REDE As USUARIO_RESPONSAVEL, CPE_CONTRATOS.NUMERO_NOTA_TECNICA, CP_ORDEM_SERVICO.FAVORECIDO_TODOS As ASSESSOR_ANALISTA, CPE_CONTRATOS.FORNECEDOR_CONTRATADO, CPE_CONTRATOS.NUMERO_DO_DGCO, CPE_CSC.FISCAL_ADM_DO_CONTRATO, CPE_CSC.FISCAL_DE_SERVICO, CPE_CSC.GESTOR_DO_CONTRATO, CPE_CSC.OBJETO_CONTRATO, CPE_CSC.NUMERO_RC, CPE_CSC.TE_MODALIDADE_CONTRATACAO As MODALIDADE_CONTRATACAO, CPE_CSC.CSC_DATA_FIM As DATA_FIM_VIGENCIA_ATUAL, CPE_CSC.CSC_DGCO As DGCO, CPE_CSC.OBSERVACAO From OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On OCORRENCIA.ID_RESPONSAVEL = PESSOA.ID_PESSOA Left Join CPE_CONTRATOS On OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Where OCORRENCIA.ID_CLASSE_SUB_PROC_INI = 347")

        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



def enviaDadosDue():
    try:
        result_table2 = DB.ExecuteDataTable("Select CP_ORDEM_SERVICO.CNPJ As CNPJ, CP_ORDEM_SERVICO.SIM_NAO As NECESSARIO_BCK_CHECK, CP_ORDEM_SERVICO.ACAO_TOMADA As JUSTIFICATIVA, OCORRENCIA.ASSUNTO As ASSUNTO, CP_ORDEM_SERVICO.NOME_FORNECEDOR As RAZAO_SOCIAL, CPE_CONTRATOS.OBS5 As INFO_COMPLEMENTARES, CPE_CSC.CSC_VALOR1_A As VALOR_ARREMATADO, CPE_CSC.DIRETORIA_GERENCIA As DIRETORIA_GERENCIA, CPE_CONTRATOS.DIVISAO_DUEDILIGENCE As AREA, CPE_CSC.FUNDAMENTACAO As FUDAMENTACAO, CPE_CONTRATOS.MODALIDADE_DE_CONTRATACAO As MODALIDADE_CONTRAT, CPE_CSC.NUMERO_DGCO As DGCO, CPE_FINANCEIRO.OBJETO_QUALIF As OBJ_RESUMIDO, CPE_DESLOCAMENTO.VALOR_DESPESAS As SOMATORIO_CONTRATACAO, CPE_FINANCEIRO.VALOR_QUALIF As VALOR_CONTRATACAO, CPE_CSC.OBS6 As AJUSTES_NECESSARIOS, CPE_CSC.DATA_HORA_FIM As DATA_ANALISE, CPE_CONTRATOS.GRAUDERISCO_DUEDILIGENCE As GRAU_DE_RISCO, CPE_CSC.OBS21 As ANALISE_DISUP, CPE_CSC.SIM_NAO1 As GRANDE_EXPOSICAOBBTS, OCORRENCIA.ID_CLASSE_SUB_PROC As ID_OCORRENCIA, CPE_DESLOCAMENTO.VALOR_PASSAGEM As VALOR_ADITIVO1, OCORRENCIA.NUMERO, OCORRENCIA.DATA_HORA_CRIACAO, OCORRENCIA.SITUACAO, OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.DATA_HORA_SOL, PESSOA.NOME, PESSOA1.NOME As GESTOR_DEMANDANTE, PESSOA2.NOME As RESPONSAVEL_AREA_CLIENTE From CP_ORDEM_SERVICO Left Join OCORRENCIA On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_CONTRATOS On CP_ORDEM_SERVICO.ID_OCORRENCIA = CPE_CONTRATOS.ID_OCORRENCIA Left Join CPE_CSC On CPE_CONTRATOS.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_FINANCEIRO On CPE_CSC.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CPE_DESLOCAMENTO On CPE_FINANCEIRO.ID_OCORRENCIA = CPE_DESLOCAMENTO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Left Join PESSOA PESSOA1 On PESSOA1.ID_PESSOA = CPE_CSC.TE_NOME_EMPREGADO Left Join PESSOA PESSOA2 On CP_ORDEM_SERVICO.FAVORECIDO_COBRA = PESSOA2.ID_PESSOA Where OCORRENCIA.ID_CLASSE_SUB_PROC = 534 Order By OCORRENCIA.NUMERO")

        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def enviaDadosCad():
    try:
        # ExecuteReader retorna um conjunto de resultados
        result_table2 = DB.ExecuteDataTable("Select F.status_matricula As STATUS_MATRICULA, F.nome As NOME, F.matricula As MATRICULA, F.gestor_posicao As GESTOR_POSICAO, F.cargo_funcional As CARGO_FUNCIONAL, F.CARGO,  F.funcao_gratificada As FUNCAO_GRATIFICADA,F.supervisor As SUPERVISOR, F.organizacao As ORGANIZACAO, F.unidade_negocio As UNIDADE_NEGOCIO, F.local_cidade As LOCAL_CIDADE,F.local_estado As LOCAL_ESTADO, F.numero_subcr_nivel1 As UOR_DIVISAO, F.descricao_subcr_nivel1 As DESCRICAO_DIVISAO, F.numero_subcr_nivel2 As UOR_GERENCIA,F.descricao_subcr_nivel2 As DESCRICAO_GERENCIA, F.numero_subcr_nivel3 As UOR_DIRETORIA, F.descricao_subcr_nivel3 As DESCRICAO_DIRETORIA, cp.DATA_NASCIMENTO As NASCIMENTO, cp.DATA_DE_ADMISSAO As ADMISSAO, P.EMAIL As EMAIL, P.USUARIO_REDE As USUARIO, P.BLOQUEADO As BLOQUEADO, c.scr_sigla As SIGLA_DIVISAO, c2.scr_sigla As SIGLA_GERENCIA, c3.scr_sigla As SIGLA_DIRETORIA From CAD_FUNCIONARIO_V F Inner Join cp_pessoa cp On F.matricula = cp.matricula Inner Join PESSOA P On cp.ID_PESSOA = P.id_pessoa Inner Join cob_gl_centro c On c.scr = F.numero_subcr_nivel1 Inner Join cob_gl_centro c2 On c2.scr = F.numero_subcr_nivel2 Inner Join cob_gl_centro c3 On c3.scr = F.numero_subcr_nivel3 Where f.CARGO_FUNCIONAL not in ('PRESTADOR DE SERVICO') And f.CARGO_FUNCIONAL IS NOT NULL Order By f.nome")
        
        
            
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data

    # Serializar a lista de pessoas para JSON
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)
        
        
        
def enviaDadosCadCompleto():
    try:
        # ExecuteReader retorna um conjunto de resultados
        result_table2 = DB.ExecuteDataTable("select * from CAD_FUNCIONARIO_V")
        
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data

    # Serializar a lista de pessoas para JSON
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)
        
        

def enviaDadosCadCompletao():
    try:
        # ExecuteReader retorna um conjunto de resultados
        result_table2 = DB.ExecuteDataTable("SELECT f.*, p.* FROM CAD_FUNCIONARIO_V f LEFT JOIN cp_pessoa cp ON f.matricula = cp.matricula LEFT JOIN pessoa p ON cp.id_pessoa = p.id_pessoa ORDER BY f.nome")
        
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data

    # Serializar a lista de pessoas para JSON
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



def enviaDadosDiv():
    try:
        
        #ExecuteReader retorna um conjunto de resultados
        result_table2 = DB.ExecuteDataTable("SELECT DISTINCT matricula_sup_nivel1 as MATRICULA_GESTOR, f.numero_subcr_nivel1 As NUMERO, f.descricao_subcr_nivel1 As DESCRICAO, c.scr_sigla As SIGLA FROM CAD_FUNCIONARIO_V F Left Join cob_gl_centro c on c.scr = f.numero_subcr_nivel1")
        
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



# R E L A T Ó R I O   D A   G E R A L
def listarChamadosAditamentosGeral():
    try:
        result_table2 = DB.ExecuteDataTable("SELECT CPE_FINANCEIRO.DGCO_BB AS DGCO, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL AS DATA_HORA_SOLICITACAO, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, OCORRENCIA.DATA_HORA_ULT_ATUA, PESSOA.NOME AS SOLICITANTE, PESSOA1.NOME AS CONDUTOR, OCORRENCIA.SITUACAO, Z_00143_ADIT_SOL.LIST_AD AS LIST_AD, OCORRENCIA.NUMERO, CLASSE_SUB_PROCESSO.SIGLA, CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO, CASE WHEN OCORRENCIA.SITUACAO = 'Aberto' THEN FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' ELSE FLOOR(OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((OCORRENCIA.DATA_HORA_FIM_REAL - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' END AS TEMPO FROM OCORRENCIA LEFT JOIN CPE_FINANCEIRO ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA LEFT JOIN PESSOA ON OCORRENCIA.ID_CLIENTE = PESSOA.ID_PESSOA LEFT JOIN PESSOA PESSOA1 ON OCORRENCIA.ID_RESPONSAVEL = PESSOA1.ID_PESSOA LEFT JOIN Z_00143_ADIT_SOL ON OCORRENCIA.ID_OCORRENCIA = Z_00143_ADIT_SOL.ID_OCORRENCIA LEFT JOIN CLASSE_SUB_PROCESSO ON OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO WHERE CPE_FINANCEIRO.DGCO_BB IS NOT NULL AND (OCORRENCIA.ID_CLASSE_SUB_PROC_INI IN (379) OR CLASSE_SUB_PROCESSO.SIGLA IN ('ADT', 'ADITAMENTOSOL'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)




def realizarReservaDgco(fisica_juridica, cpf_cnpj, razao_social, descricao, matricula_solicitante, objeto):
    try:
        matriculaFiscalServ = matricula_solicitante
        id = 0
        colaboradores4 = DB.ExecuteDataTable("Select PESSOA.ID_PESSOA, PESSOA.NOME, CP_PESSOA.MATRICULA From PESSOA Inner Join CP_PESSOA On PESSOA.ID_PESSOA = CP_PESSOA.ID_PESSOA Where CP_PESSOA.MATRICULA = '" + matriculaFiscalServ.ToString()+"'")
 
        
        for row in colaboradores4.Rows:
            id = row["ID_PESSOA"]
        
        # Corrigido o argumento do assunto
        novaOS = OrdemServico.Nova(OrdemServico.Carrega('Numero', 589), "SOLICITRESERVDG", "RESERVDGCO", "Solicitação de Reserva DGCO - Dilic", Servico.Carrega(998), Pessoa.Carrega(id), Pessoa.Carrega(26709))
        
        novaOS.SetCustom('COMBOBOX1', 'Fornecedor')
        novaOS.DescricaoDetalhada = descricao
        
        novaOS.SetCustom('RAZAO_SOCIAL_CLIENTE', razao_social)
        novaOS.SetCustom('OBJETO_CONTRATACAO', objeto.ToString())
        
        if fisica_juridica == 'fisica':
            novaOS.SetCustom('CSC_CPF', cpf_cnpj)
            novaOS.ModificaCampoFormularioVisivel('CSC_CPF', True)
            novaOS.ModificaCampoFormularioVisivel('CNPJ', False)
            novaOS.SetCustom('JURIDICA_FISICA', 'Pessoa Física')
        else:
            novaOS.SetCustom('CNPJ', cpf_cnpj)
            novaOS.ModificaCampoFormularioVisivel('CNPJ', True)
            novaOS.ModificaCampoFormularioVisivel('CSC_CPF', False)
            novaOS.SetCustom('JURIDICA_FISICA', 'Pessoa Jurídica')
        
        
        novaOS.Salva()
        novaOS.AvancaAtividade()
        # Serializando o tipo de novaOS
        json_data = JsonConvert.SerializeObject([str(novaOS.Numero)])
        return json_data

    except Exception as e:
        return e.ToString()
        
        
def buscarDgco(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select CPE_CSC.CSC_DGCO From OCORRENCIA Inner Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Where OCORRENCIA.NUMERO = '"+numeroOs+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



        
def encaminharOs(os, idPessoa):
    try:
        lista = Utils.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA, ORDEM_SERVICO.ID_OCORRENCIA, OCORRENCIA.NUMERO From OCORRENCIA Inner Join ORDEM_SERVICO On ORDEM_SERVICO.ID_OCORRENCIA = OCORRENCIA.ID_OCORRENCIA Where OCORRENCIA.NUMERO ='" + os + "'")

        idOcorrencia = 0
        for linha in lista.Rows:
            idOcorrencia = linha["ID_OCORRENCIA"]
               
        chamado = OrdemServico.Carrega(Convert.ToInt32(idOcorrencia))

        
        idCliente = idPessoa
        
        
        chamado.Favorecido = Pessoa.Carrega(Convert.ToInt32(idCliente))
        chamado.Responsavel = chamado.Favorecido

        chamado.Salva()
        
        
        return JsonConvert.SerializeObject(True)
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)
    



def enviaDadosColaborador():
    try:
        # ExecuteReader retorna um conjunto de resultados
        result_table2 = DB.ExecuteDataTable("Select PESSOA.ID_PESSOA, PESSOA.NOME, PESSOA.USUARIO_REDE, CP_PESSOA.MATRICULA, PESSOA.ATIVO From PESSOA Left Join CP_PESSOA On PESSOA.ID_PESSOA = CP_PESSOA.ID_PESSOA Order By PESSOA.NOME,  PESSOA.ID_PESSOA")
        

        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data

        # Serializar a lista de pessoas para JSON
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)
        
        

        
def validarOrdemServico(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_FIM_REAL, OCORRENCIA.MOTIVO_CANCELAMENTO, OCORRENCIA.ID_RESPONSAVEL, OCORRENCIA.SITUACAO From OCORRENCIA  Where OCORRENCIA.NUMERO = '" + numeroOs + "'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)
     
   
def alterarSituacao(situacao, os, motivo):
    try:
        

        lista = Utils.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA, ORDEM_SERVICO.ID_OCORRENCIA, OCORRENCIA.NUMERO From OCORRENCIA Inner Join ORDEM_SERVICO On ORDEM_SERVICO.ID_OCORRENCIA = OCORRENCIA.ID_OCORRENCIA Where OCORRENCIA.NUMERO ='" + os + "'")

        idOcorrencia = 0
        for linha in lista.Rows:
            idOcorrencia = linha["ID_OCORRENCIA"]
               
        chamado = OrdemServico.Carrega(Convert.ToInt32(idOcorrencia))

        if situacao == "Aberto":
            chamado.Situacao = "Aberto"
        elif situacao == "FinalizadaSucesso":
            chamado.Situacao = "FinalizadaSucesso"
        elif situacao == "Cancelado":
            if motivo != '':
                chamado.Cancela(motivo.ToString())
            else:
                chamado.Cancela('OS Cancelada com Sucesso!')
        else:
            raise Exception("Situação inválida.")

        chamado.Salva()
        
        
        return JsonConvert.SerializeObject(True)
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)
        
        

        
def buscarDadosOsGeral(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select RESP.NOME As RESPONSAVEL, OCORRENCIA.ASSUNTO, OCORRENCIA.ID_CLIENTE, OCORRENCIA.ID_RESPONSAVEL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, COSTUMER.NOME As CLIENTE From OCORRENCIA Left Join PESSOA RESP On OCORRENCIA.ID_RESPONSAVEL = RESP.ID_PESSOA Left Join PESSOA COSTUMER On OCORRENCIA.ID_CLIENTE = COSTUMER.ID_PESSOA Where OCORRENCIA.NUMERO = '"+numeroOs+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)
        
        

        
        
        
def atualizarAtividade(comando, os):
    try:
        

        lista = Utils.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA, ORDEM_SERVICO.ID_OCORRENCIA, OCORRENCIA.NUMERO From OCORRENCIA Inner Join ORDEM_SERVICO On ORDEM_SERVICO.ID_OCORRENCIA = OCORRENCIA.ID_OCORRENCIA Where OCORRENCIA.NUMERO ='" + os + "'")

        idOcorrencia = 0
        for linha in lista.Rows:
            idOcorrencia = linha["ID_OCORRENCIA"]
               
        chamado = OrdemServico.Carrega(Convert.ToInt32(idOcorrencia))


        if comando == "Avanca":
            chamado.AvancaAtividade()
        elif situacao == "Voltar":
            chamado.VoltaAtividade()
        else:
            raise Exception("Situação inválida.")

        chamado.Salva()
        
        
        return JsonConvert.SerializeObject(True)
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)
        
        
        

        
        
        
def apiPrimeiraDesignacao(dgco, razao_social, obj, comissao, matricula_gestor, uorGestor):
    try:
        

        idGestor = 0
        nomeGestor = ''
        uorId = 0
        gestor = DB.ExecuteDataTable("Select PESSOA.ID_PESSOA, PESSOA.NOME, CP_PESSOA.MATRICULA From PESSOA Inner Join CP_PESSOA On PESSOA.ID_PESSOA = CP_PESSOA.ID_PESSOA Where CP_PESSOA.MATRICULA = '" + matricula_gestor.ToString()+"'")
        
        for row in gestor.Rows:
            idGestor = row["ID_PESSOA"]
            nomeGestor = row["NOME"]
            
            
            
        uor = DB.ExecuteDataTable("Select ORGAO.ID_ORGAO, ORGAO.SIGLA, ORGAO.DESCRICAO, ORGAO.ID_GESTOR, ORGAO.ATIVO From ORGAO Where ORGAO.SIGLA = '" + uorGestor.ToString()+"'")
        
        for row in uor.Rows:
            uorId = row["DESCRICAO"]

        
        
        # Corrigido o argumento do assunto
        novaOS = OrdemServico.Nova(OrdemServico.Carrega('Numero', 654), "DESIGNACAODEINTERVENIENTES", "APIDESIGNACAOSUPRAVIZIO", "Designação de Intervenientes", Servico.Carrega(1482), Pessoa.Carrega(idGestor), Pessoa.Carrega(idGestor))
        
        
        

        
        novaOS.SetCustom('DGCO_BB', str(dgco))
        novaOS.SetCustom('NOME_FORNECEDOR', razao_social.ToString())
        novaOS.SetCustom('OBJETO_CONTRATACAO', obj.ToString())
        novaOS.SetCustom('SIM_NAO3', comissao.ToString())
        novaOS.SetCustom('FAVORECIDO_GESTOR', str(nomeGestor))
        novaOS.SetCustom('MATRICULA_GESTOR_TITULAR', str(matricula_gestor))
        
        novaOS.SetCustom('SCR_TODOS_RH', uorId.ToString())
        
        novaOS.DescricaoDetalhada = 'Designação Inicial de Fiscais de Serviço e Gestor Suplente!'
        
        
        

        novaOS.Salva()
        novaOS.AvancaAtividade()
        
        # Serializando o tipo de novaOS
        json_data = JsonConvert.SerializeObject([str(novaOS.Numero)])
        return json_data

    except Exception as e:
        return e.ToString()
        

    
    

def apiPrimeiraDesignacaoAdministrativo(dgco, razao_social, obj):
    try:
        
        idGestorCsc = 0
        nomeGestorCsc = ''
        matriculaGestorCsc = 0
        emailGerenteCsc = ''
        
        tableCsc = DB.ExecuteDataTable("Select ID_GESTOR From ORGAO WHERE ORGAO.SIGLA = '3000003341'")
        for row2 in tableCsc.Rows:
            idGestorCsc = row2['ID_GESTOR']
            

            
        gestorCsc = DB.ExecuteDataTable("Select PESSOA.ID_PESSOA, PESSOA.EMAIL, PESSOA.NOME, CP_PESSOA.MATRICULA From PESSOA Inner Join CP_PESSOA On PESSOA.ID_PESSOA = CP_PESSOA.ID_PESSOA Where CP_PESSOA.ID_PESSOA = '" + idGestorCsc.ToString()+"'")

        for row in gestorCsc.Rows:
            matriculaGestorCsc = row["MATRICULA"]
            nomeGestorCsc = row["NOME"]
            emailGerenteCsc = str(row['EMAIL'])
            

        
        
            
        
        #Corrigido o argumento do assunto
        novaOS = OrdemServico.Nova(OrdemServico.Carrega('Numero', 654), "DESIGNACAODEINTERVENIENTES", "APIDESIGNACAOSUPRAVIZIO2", "Designação de Intervenientes", Servico.Carrega(1482), Pessoa.Carrega(idGestorCsc), Pessoa.Carrega(idGestorCsc))
        
        
        
        
        
        novaOS.SetCustom('DGCO_BB', str(dgco))
        novaOS.SetCustom('NOME_FORNECEDOR', razao_social.ToString())
        novaOS.SetCustom('OBS21', obj.ToString())
        novaOS.SetCustom('FAVORECIDO_GESTOR', str(nomeGestorCsc))
        novaOS.SetCustom('MATRICULA_GESTOR_TITULAR', str(matriculaGestorCsc))
        
        
        novaOS.DescricaoDetalhada = 'Designação Inicial de Fiscais Administrativos!'
        

        novaOS.Salva()
        novaOS.AvancaAtividade()
        
        # Serializando o tipo de novaOS
        
        json_data = JsonConvert.SerializeObject([
            {
                "numero_os": str(novaOS.Numero),
                "nome_gestor": nomeGestorCsc,
                "email_gestor": emailGerenteCsc
            }
        ])
        return json_data


    except Exception as e:
        return e.ToString()
