# dicoc
# Caminho: Catálogo > Biblioteca de scripts > dicoc
# Fonte: Gestão_de_Pessoas_-_Benefícios_Versão_90_Reembolso.xml (2 variantes entre os XMLs; esta é a mais recente)

import clr
import System
clr.AddReference("System.Data")
from System.Data import DataSet 
clr.AddReference("Newtonsoft.Json")
from Newtonsoft.Json import * 
from System.Text import StringBuilder
from System.Web import *

from Venki.Supravizio.Processo.Custom import OrdemServico
from Venki.Supravizio.Processo.Custom import Servico
from Venki.Supravizio.Recurso.Custom import Pessoa
        




        
def listarSolicitacoesNotificacao():
    try:
        projetos = [];
        
        # ExecuteReader retorna um conjunto de resultados 
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.SITUACAO, CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO, OCORRENCIA.DATA_HORA_SOL, CPE_CSC.OBJETO_CONTRATO, CPE_CSC.CSC_DATA_FIM, CPE_CSC.CSC_DGCO, CPE_CSC.OBSERVACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME As FISCAL_DE_SERVICO, PESSOA1.NOME As FISCAL_ADM_DO_CONTRATO, PESSOA2.NOME As GESTOR_DO_CONTRATO, OCORRENCIA.ID_OCORRENCIA, PESSOA3.NOME As RESPONSAVEL, PESSOA3.USUARIO_REDE As USUARIO_RESPONSAVEL From OCORRENCIA Left Join CLASSE_SUB_PROCESSO On CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = OCORRENCIA.ID_CLASSE_SUB_PROC_INI Inner Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Inner Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Inner Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Inner Join PESSOA On PESSOA.ID_PESSOA = CPE_CSC.FISCAL_DE_SERVICO Inner Join PESSOA PESSOA1 On PESSOA1.ID_PESSOA = CPE_CSC.FISCAL_ADM_DO_CONTRATO Inner Join PESSOA PESSOA2 On PESSOA2.ID_PESSOA = CPE_CSC.GESTOR_DO_CONTRATO Inner Join PESSOA PESSOA3 On PESSOA3.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Where CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = 1120")
        
        
        
        
        for row in result_table2.Rows:
            projeto = {
                "identificador": row["ID_OCORRENCIA"],
                "numero": row["NUMERO"],
                "assunto": row["ASSUNTO"],
                "situacao": row["SITUACAO"],
                "dataHoraSolicitacao": row["DATA_HORA_SOL"],
                "fiscalServico": row["FISCAL_DE_SERVICO"],
                "fiscalAdmContrato": row["FISCAL_ADM_DO_CONTRATO"],
                "gestorContrato": row["GESTOR_DO_CONTRATO"],
                "objetoContrato": row["OBJETO_CONTRATO"],
                "fimVigenciaContrato": row["CSC_DATA_FIM"],
                "dgco": row["CSC_DGCO"],
                "observacao": row["OBSERVACAO"],
                "nomeFornecedor": row["NOME_FORNECEDOR"],
                "descricaoDetalhada": row["DESCRICAO_DETALHADA"],
                "responsavel": row["RESPONSAVEL"],
                "usuarioResponsavel": row["USUARIO_RESPONSAVEL"]
            }
            
            projetos.append(projeto)
            
        
        # Verificar se a lista de projetos está vazia
        if len(projetos) == 0:
            return "Nenhuma solicitação encontrada."

        # Serializar a lista de projetos para JSON
        json_data = JsonConvert.SerializeObject(projetos)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)
        
        
        
        
        
def relatorioRepactuacoes(): ###Trocar os IDS PARA OS CHAMADOS DA DICOC
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.SITUACAO, CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO, OCORRENCIA.DATA_HORA_SOL, CPE_CSC.OBJETO_CONTRATO, CPE_CSC.CSC_DATA_FIM, CPE_CSC.CSC_DGCO, CPE_CSC.OBSERVACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME As FISCAL_DE_SERVICO, PESSOA1.NOME As FISCAL_ADM_DO_CONTRATO, PESSOA2.NOME As GESTOR_DO_CONTRATO, OCORRENCIA.ID_OCORRENCIA, PESSOA3.NOME As RESPONSAVEL, PESSOA3.USUARIO_REDE As USUARIO_RESPONSAVEL, CPE_FINANCEIRO.DGCO_BB From OCORRENCIA Left Join CLASSE_SUB_PROCESSO On CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = OCORRENCIA.ID_CLASSE_SUB_PROC_INI Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = CPE_CSC.FISCAL_DE_SERVICO Left Join PESSOA PESSOA1 On PESSOA1.ID_PESSOA = CPE_CSC.FISCAL_ADM_DO_CONTRATO Left Join PESSOA PESSOA2 On PESSOA2.ID_PESSOA = CPE_CSC.GESTOR_DO_CONTRATO Left Join PESSOA PESSOA3 On PESSOA3.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Inner Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Where CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = 421")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)




def listarChamadosAbertos(): ###Trocar os IDS PARA OS CHAMADOS DA DICOC
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_ULT_ATUA, PESSOA.NOME As RESPONSAVEL, PESSOA.USUARIO_REDE, FLOOR(SYSDATE - OCORRENCIA.DATA_HORA_SOL) || ' dias e ' || FLOOR(MOD((SYSDATE - OCORRENCIA.DATA_HORA_SOL) * 24, 24)) || ' horas' AS TEMPO_EM_ABERTO From OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Where OCORRENCIA.SITUACAO = 'Aberto' And (CLASSE_SUB_PROCESSO.SIGLA In ('ASSINATURACONTRATOSADITIVOS', 'ACIONAATAASSINA', 'ATESTADOCAPACIDADE', 'CADCONTRAOKS', 'DESIGNACTRCLIENTE', 'DISTRATO', 'DISTRCLIENTES','ADITIVOSCLIENTES', 'PROCUNIFCONT', 'TERMOCONTRATOCLIENT') or OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (336, 702, 513, 333, 528, 289, 715, 335, 272, 703)) Order By OCORRENCIA.DATA_HORA_SOL")
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)

        

        

# T E R M O S   D E S I G N A Ç Ã O
def buscarChamadosTermo():
    try:
        result_table2 = DB.ExecuteDataTable("Select CPE_CSC.CSC_NUMERO As NUMERO_CONTRATO, CPE_NEGOCIOS.RAZAO_SOCIAL_CLIENTE As NOME_CONTRATO, OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CPE_FINANCEIRO1.DGCO_BB As DGCO, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO, CPE_CONTRATOS02.TIPO_DESIGNACAO_INTERV, CPE_CONTRATOS02.DESIGNA_TITU_OR_SUP, PESSOA.NOME As DESIGNADO From OCORRENCIA left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_NEGOCIOS On OCORRENCIA.ID_OCORRENCIA = CPE_NEGOCIOS.ID_OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO CPE_FINANCEIRO1 On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA Left Join CPE_CONTRATOS02 On OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = CASE WHEN REGEXP_LIKE(CP_ORDEM_SERVICO.FAVORECIDO_ALL, '^[0-9]+$') THEN TO_NUMBER(CP_ORDEM_SERVICO.FAVORECIDO_ALL) ELSE NULL END Where OCORRENCIA.ID_CLASSE_SUB_PROC_INI = 1364")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarTermosPorOs(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select CPE_CSC.CSC_NUMERO As NUMERO_CONTRATO, CPE_NEGOCIOS.RAZAO_SOCIAL_CLIENTE As NOME_CONTRATO, OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CPE_FINANCEIRO1.DGCO_BB As DGCO, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO, CPE_CONTRATOS02.TIPO_DESIGNACAO_INTERV, CPE_CONTRATOS02.DESIGNA_TITU_OR_SUP, PESSOA.NOME As DESIGNADO From OCORRENCIA left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_NEGOCIOS On OCORRENCIA.ID_OCORRENCIA = CPE_NEGOCIOS.ID_OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO CPE_FINANCEIRO1 On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA Left Join CPE_CONTRATOS02 On OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = CASE WHEN REGEXP_LIKE(CP_ORDEM_SERVICO.FAVORECIDO_ALL, '^[0-9]+$') THEN TO_NUMBER(CP_ORDEM_SERVICO.FAVORECIDO_ALL) ELSE NULL END Where OCORRENCIA.ID_CLASSE_SUB_PROC_INI = 1364 AND OCORRENCIA.NUMERO LIKE '%{}%'".format(numeroOs))
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesTermo(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select CPE_CSC.CSC_NUMERO As NUMERO_CONTRATO, CPE_NEGOCIOS.RAZAO_SOCIAL_CLIENTE As NOME_CONTRATO, OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CPE_FINANCEIRO1.DGCO_BB As DGCO, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO, CPE_CONTRATOS02.TIPO_DESIGNACAO_INTERV, CPE_CONTRATOS02.DESIGNA_TITU_OR_SUP, PESSOA.NOME As DESIGNADO From OCORRENCIA left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_NEGOCIOS On OCORRENCIA.ID_OCORRENCIA = CPE_NEGOCIOS.ID_OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO CPE_FINANCEIRO1 On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA Left Join CPE_CONTRATOS02 On OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = CASE WHEN REGEXP_LIKE(CP_ORDEM_SERVICO.FAVORECIDO_ALL, '^[0-9]+$') THEN TO_NUMBER(CP_ORDEM_SERVICO.FAVORECIDO_ALL) ELSE NULL END Where OCORRENCIA.ID_CLASSE_SUB_PROC_INI = 1364 And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



# D E S I G N A Ç Ã O
def buscarChamadosDesignacao():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CPE_NEGOCIOS.RAZAO_SOCIAL_CLIENTE As NOME_CONTRATO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CPE_CSC.CSC_NUMERO As NUMERO_CONTRATO, CPE_CSC.CSC_DGCO As DGCO, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO From OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO CPE_FINANCEIRO1 On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_NEGOCIOS On OCORRENCIA.ID_OCORRENCIA = CPE_NEGOCIOS.ID_OCORRENCIA Where OCORRENCIA.ID_CLASSE_SUB_PROC_INI = 588 Order By OCORRENCIA.ID_OCORRENCIA")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesDesignacao(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CPE_NEGOCIOS.RAZAO_SOCIAL_CLIENTE As NOME_CONTRATO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CPE_CSC.CSC_NUMERO As NUMERO_CONTRATO, CPE_CSC.CSC_DGCO As DGCO, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO From OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO CPE_FINANCEIRO1 On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_NEGOCIOS On OCORRENCIA.ID_OCORRENCIA = CPE_NEGOCIOS.ID_OCORRENCIA Where OCORRENCIA.ID_CLASSE_SUB_PROC_INI = 588 And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)
        
        
        
        
# ASSINATURA ATA
def buscarChamadosAssinaturaAta():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CPE_NEGOCIOS.RAZAO_SOCIAL_CLIENTE As NOME_CONTRATO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CPE_CSC.CSC_NUMERO As NUMERO_CONTRATO, CPE_CSC.CSC_DGCO As DGCO, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO From OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO CPE_FINANCEIRO1 On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_NEGOCIOS On OCORRENCIA.ID_OCORRENCIA = CPE_NEGOCIOS.ID_OCORRENCIA Where OCORRENCIA.ID_CLASSE_SUB_PROC_INI = 1359 Order By OCORRENCIA.ID_OCORRENCIA")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesAssinaturaAta(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CPE_NEGOCIOS.RAZAO_SOCIAL_CLIENTE As NOME_CONTRATO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CPE_CSC.CSC_NUMERO As NUMERO_CONTRATO, CPE_CSC.CSC_DGCO As DGCO, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO From OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO CPE_FINANCEIRO1 On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_NEGOCIOS On OCORRENCIA.ID_OCORRENCIA = CPE_NEGOCIOS.ID_OCORRENCIA Where OCORRENCIA.ID_CLASSE_SUB_PROC_INI = 1359 And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)
        
        
    
        
# ASSINATURA NOVOS CONTRATOS E ADITIVOS
def buscarChamadosAssinatura():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CPE_NEGOCIOS.RAZAO_SOCIAL_CLIENTE As NOME_CONTRATO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CPE_CSC.CSC_NUMERO As NUMERO_CONTRATO, CPE_CSC.CSC_DGCO As DGCO, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO From OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO CPE_FINANCEIRO1 On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_NEGOCIOS On OCORRENCIA.ID_OCORRENCIA = CPE_NEGOCIOS.ID_OCORRENCIA Where OCORRENCIA.ID_CLASSE_SUB_PROC_INI = 336 Order By OCORRENCIA.ID_OCORRENCIA")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesAssinatura(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CPE_NEGOCIOS.RAZAO_SOCIAL_CLIENTE As NOME_CONTRATO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CPE_CSC.CSC_NUMERO As NUMERO_CONTRATO, CPE_CSC.CSC_DGCO As DGCO, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO From OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO CPE_FINANCEIRO1 On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_NEGOCIOS On OCORRENCIA.ID_OCORRENCIA = CPE_NEGOCIOS.ID_OCORRENCIA Where OCORRENCIA.ID_CLASSE_SUB_PROC_INI = 336 And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)
        
        
        
        
    
# ATESTADO DE CAPACIDADE TÉCNICA CLIENTES
def buscarChamadosAtestadoClientes():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CPE_CSC.CSC_NUMERO As NUMERO_CONTRATO, CPE_CSC.CSC_DGCO As DGCO, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CPE_CSC.NOME_CONTRATO, CPE_ORDEM_SERVICO.CLIENTE As NOME_FORNECEDOR From OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO CPE_FINANCEIRO1 On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_NEGOCIOS On OCORRENCIA.ID_OCORRENCIA = CPE_NEGOCIOS.ID_OCORRENCIA Inner Join CPE_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CPE_ORDEM_SERVICO.ID_OCORRENCIA Where OCORRENCIA.ID_CLASSE_SUB_PROC_INI = 927 Order By OCORRENCIA.ID_OCORRENCIA")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesAtestadoClientes(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CPE_CSC.CSC_NUMERO As NUMERO_CONTRATO, CPE_CSC.CSC_DGCO As DGCO, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CPE_CSC.NOME_CONTRATO, CPE_ORDEM_SERVICO.CLIENTE As NOME_FORNECEDOR From OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO CPE_FINANCEIRO1 On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_NEGOCIOS On OCORRENCIA.ID_OCORRENCIA = CPE_NEGOCIOS.ID_OCORRENCIA Inner Join CPE_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CPE_ORDEM_SERVICO.ID_OCORRENCIA Where OCORRENCIA.ID_CLASSE_SUB_PROC_INI = 927 And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)
        
        
        
        
        
# CADASTRAR NO OKS
def buscarChamadosCadastrarOks():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CPE_CSC.CSC_NUMERO As NUMERO_CONTRATO, CPE_CSC.CSC_DGCO As DGCO, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO, CPE_CSC.NOME_CONTRATO, CPE_ORDEM_SERVICO.CLIENTE As NOME_FORNECEDOR From OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO CPE_FINANCEIRO1 On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_NEGOCIOS On OCORRENCIA.ID_OCORRENCIA = CPE_NEGOCIOS.ID_OCORRENCIA Inner Join CPE_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CPE_ORDEM_SERVICO.ID_OCORRENCIA Where OCORRENCIA.ID_CLASSE_SUB_PROC_INI = 333 Order By OCORRENCIA.ID_OCORRENCIA")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesCadastrarOks(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CPE_CSC.CSC_NUMERO As NUMERO_CONTRATO, CPE_CSC.CSC_DGCO As DGCO, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO, CPE_CSC.NOME_CONTRATO, CPE_ORDEM_SERVICO.CLIENTE As NOME_FORNECEDOR From OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO CPE_FINANCEIRO1 On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_NEGOCIOS On OCORRENCIA.ID_OCORRENCIA = CPE_NEGOCIOS.ID_OCORRENCIA Inner Join CPE_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CPE_ORDEM_SERVICO.ID_OCORRENCIA Where OCORRENCIA.ID_CLASSE_SUB_PROC_INI = 333 And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)
        
        
        
    
# DISTRATO CLIENTE
def buscarChamadosDistratoCliente():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO, CP_ORDEM_SERVICO.NUM_CONTRATO As NUMERO_CONTRATO From OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO CPE_FINANCEIRO1 On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_NEGOCIOS On OCORRENCIA.ID_OCORRENCIA = CPE_NEGOCIOS.ID_OCORRENCIA Where OCORRENCIA.ID_CLASSE_SUB_PROC_INI = 289 Order By OCORRENCIA.ID_OCORRENCIA")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesDistratoCliente(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO, CP_ORDEM_SERVICO.NUM_CONTRATO As NUMERO_CONTRATO From OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO CPE_FINANCEIRO1 On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_NEGOCIOS On OCORRENCIA.ID_OCORRENCIA = CPE_NEGOCIOS.ID_OCORRENCIA Where OCORRENCIA.ID_CLASSE_SUB_PROC_INI = 289 And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)
        
        
        
        
        
        
        
# NEGOCIACAO
def buscarChamadosNegociacaoAditivo():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, ORDEM_SERVICO.JUSTIFICATIVA From OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO CPE_FINANCEIRO1 On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_NEGOCIOS On OCORRENCIA.ID_OCORRENCIA = CPE_NEGOCIOS.ID_OCORRENCIA Inner Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Where OCORRENCIA.ID_CLASSE_SUB_PROC_INI = 335 Order By OCORRENCIA.ID_OCORRENCIA")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesNegociacaoAditivo(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, ORDEM_SERVICO.JUSTIFICATIVA From OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO CPE_FINANCEIRO1 On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_NEGOCIOS On OCORRENCIA.ID_OCORRENCIA = CPE_NEGOCIOS.ID_OCORRENCIA Inner Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Where OCORRENCIA.ID_CLASSE_SUB_PROC_INI = 335 And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)
        
        
        
        
        
        
        
# REEQUILIBRIO
def buscarChamadosReequilibrioCliente():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CPE_CSC.CSC_DGCO As DGCO, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CP_ORDEM_SERVICO.NUM_CONTRATO As NUMERO_CONTRATO From OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO CPE_FINANCEIRO1 On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_NEGOCIOS On OCORRENCIA.ID_OCORRENCIA = CPE_NEGOCIOS.ID_OCORRENCIA Where OCORRENCIA.ID_CLASSE_SUB_PROC_INI = 272 Order By OCORRENCIA.ID_OCORRENCIA")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesReequilibrioCliente(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CPE_CSC.CSC_DGCO As DGCO, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CP_ORDEM_SERVICO.NUM_CONTRATO As NUMERO_CONTRATO From OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO CPE_FINANCEIRO1 On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_NEGOCIOS On OCORRENCIA.ID_OCORRENCIA = CPE_NEGOCIOS.ID_OCORRENCIA Where OCORRENCIA.ID_CLASSE_SUB_PROC_INI = 272 And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)
