# teste
# Caminho: Catálogo > Biblioteca de scripts > teste
# Fonte: Gestão_de_Pessoas_-_Benefícios_Versão_90_Reembolso.xml

import clr
import System
clr.AddReference("System.Data")
from System.Data import DataSet 
clr.AddReference("Newtonsoft.Json")
from Newtonsoft.Json import * 
from System.Text import StringBuilder
from System.Web import *

from Newtonsoft.Json import JsonConvert
from Newtonsoft.Json.Linq import JArray, JValue

from Venki.Supravizio.Processo.Custom import OrdemServico
from Venki.Supravizio.Processo.Custom import Servico
from Venki.Supravizio.Recurso.Custom import Pessoa
from System import Convert
        

# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# NEW STUFFS

# T O D O S   O S   C H A M A D O S ABERTOS
def listarChamadosAbertos():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_ULT_ATUA, PESSOA.NOME As RESPONSAVEL, OCORRENCIA.ID_CLASSE_SUB_PROC_INI As IDENTIFICADOR_PROCESSO, PESSOA.USUARIO_REDE, Coalesce(CPE_CSC.CSC_DGCO, CPE_CSC.NUMERO_DGCO, CPE_FINANCEIRO.DGCO_BB) As CSC_DGCO, OCORRENCIA.ID_OCORRENCIA, CLASSE_SUB_PROCESSO.SIGLA From OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Where OCORRENCIA.SITUACAO = 'Aberto' And (CLASSE_SUB_PROCESSO.SIGLA In ('ADT', 'ANGACOL', 'ANALISEPROJETOBASICO', 'ALTERARDADOSBANCARIOS', 'AVFOR', 'AVALIAFISCASERVICOOO', 'ROTINAAVALIACAO', 'AVSENCERRACONTRATO', 'DESIGNASISCCON2', 'DESIGNACAOSISCONNN', '423', 'DISTRATOERESCI', 'EMISSAOATESTADOFORNECEDOR', 'NOTIFICAFORNECEDORADITAMENTO2', 'ONBOARD', 'PROCESSADM', 'REVISAOOC', 'TERMOACEITEDESIGNACAOO', 'TERMOINTERVCONTRAT', 'ANAGARANCONT', 'AUTORIZARALTDADOSBANC', 'AVALIFORNECEDORES', 'AVISOENCERRACONT', 'DESIGNACAODEINTERVENIENTES', 'DISTRATOERESCISAO', 'ATESTADOCAPTECFORNECEDOR', 'NOTIFICACOESFORNECEDOR', 'ADITAMENTOSOL', 'TERMODEDESIGNACAO', 'ENCERRAMENTODECONTRATO') or OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (600, 379, 395, 598, 380, 536, 357, 348, 625, 637, 654, 635, 641, 659, 658, 640, 655, 404, 327))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:  
        return "Erro ao executar a consulta: " + str(e)



# T O D O S   O S   C H A M A D O S
def listarChamados():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_ULT_ATUA, PESSOA.NOME As RESPONSAVEL, OCORRENCIA.ID_CLASSE_SUB_PROC_INI As IDENTIFICADOR_PROCESSO, PESSOA.USUARIO_REDE, Coalesce(CPE_CSC.CSC_DGCO, CPE_CSC.NUMERO_DGCO, CPE_FINANCEIRO.DGCO_BB) As CSC_DGCO, OCORRENCIA.ID_OCORRENCIA, CLASSE_SUB_PROCESSO.SIGLA From OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Where OCORRENCIA.SITUACAO != 'Aberto' And (CLASSE_SUB_PROCESSO.SIGLA In ('ADT', 'ANGACOL', 'ANALISEPROJETOBASICO', 'ALTERARDADOSBANCARIOS', 'AVSENCERRACONTRATO', '423', 'DISTRATOERESCI', 'EMISSAOATESTADOFORNECEDOR', 'NOTIFICAFORNECEDORADITAMENTO2', 'PROCESSADM', 'REVISAOOC', 'ANAGARANCONT', 'AUTORIZARALTDADOSBANC', 'AVISOENCERRACONT', 'DISTRATOERESCISAO', 'ATESTADOCAPTECFORNECEDOR', 'NOTIFICACOESFORNECEDOR', 'ADITAMENTOSOL', 'ENCERRAMENTODECONTRATO') or OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (600, 379, 395, 598, 380, 536, 357, 348, 625, 659, 404, 327))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)





# S O L I C I T A Ç Õ E S   D E   N O T I F I C A Ç Ã O
def listarSolicitacoesNotificacao():
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_ULT_ATUA, CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO, OCORRENCIA.DATA_HORA_SOL, CPE_CSC.OBJETO_CONTRATO, CPE_CSC.CSC_DATA_FIM, CPE_CSC.CSC_DGCO, CPE_CSC.OBSERVACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME AS FISCAL_DE_SERVICO, PESSOA1.NOME AS FISCAL_ADM_DO_CONTRATO, PESSOA2.NOME AS GESTOR_DO_CONTRATO, OCORRENCIA.ID_OCORRENCIA, PESSOA3.NOME AS RESPONSAVEL, PESSOA3.USUARIO_REDE AS USUARIO_RESPONSAVEL, CLASSE_SUB_PROCESSO.SIGLA, CPE_CONTRATOS02.CLAUSULA_CONTRATUAL_DESCUMPRIDA FROM OCORRENCIA LEFT JOIN CLASSE_SUB_PROCESSO ON CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = OCORRENCIA.ID_CLASSE_SUB_PROC_INI LEFT JOIN CPE_CSC ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN PESSOA ON PESSOA.ID_PESSOA = CPE_CSC.FISCAL_DE_SERVICO LEFT JOIN PESSOA PESSOA1 ON PESSOA1.ID_PESSOA = CPE_CSC.FISCAL_ADM_DO_CONTRATO LEFT JOIN PESSOA PESSOA2 ON PESSOA2.ID_PESSOA = CPE_CSC.GESTOR_DO_CONTRATO LEFT JOIN PESSOA PESSOA3 ON PESSOA3.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL LEFT JOIN CPE_CONTRATOS02 ON OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA WHERE (CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO IN (600) OR CLASSE_SUB_PROCESSO.SIGLA IN ('NOTIFICAFORNECEDORADITAMENTO2', 'NOTIFICACOESFORNECEDOR'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesSolicitacaoNotificacao(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_ULT_ATUA, CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO, OCORRENCIA.DATA_HORA_SOL, CPE_CSC.OBJETO_CONTRATO, CPE_CSC.CSC_DATA_FIM, CPE_CSC.CSC_DGCO, CPE_CSC.OBSERVACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME AS FISCAL_DE_SERVICO, PESSOA1.NOME AS FISCAL_ADM_DO_CONTRATO, PESSOA2.NOME AS GESTOR_DO_CONTRATO, OCORRENCIA.ID_OCORRENCIA, PESSOA3.NOME AS RESPONSAVEL, PESSOA3.USUARIO_REDE AS USUARIO_RESPONSAVEL, CLASSE_SUB_PROCESSO.SIGLA, CPE_CONTRATOS02.CLAUSULA_CONTRATUAL_DESCUMPRIDA FROM OCORRENCIA LEFT JOIN CLASSE_SUB_PROCESSO ON CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = OCORRENCIA.ID_CLASSE_SUB_PROC_INI LEFT JOIN CPE_CSC ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN PESSOA ON PESSOA.ID_PESSOA = CPE_CSC.FISCAL_DE_SERVICO LEFT JOIN PESSOA PESSOA1 ON PESSOA1.ID_PESSOA = CPE_CSC.FISCAL_ADM_DO_CONTRATO LEFT JOIN PESSOA PESSOA2 ON PESSOA2.ID_PESSOA = CPE_CSC.GESTOR_DO_CONTRATO LEFT JOIN PESSOA PESSOA3 ON PESSOA3.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL LEFT JOIN CPE_CONTRATOS02 ON OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA WHERE (CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO IN (600) OR CLASSE_SUB_PROCESSO.SIGLA IN ('NOTIFICAFORNECEDORADITAMENTO2', 'NOTIFICACOESFORNECEDOR')) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)






# S O L I C I T A Ç Õ E S   D E   A D I T A M E N T O
def listarSolicitacoesAditamento():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_ULT_ATUA, CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO, OCORRENCIA.DATA_HORA_SOL, CPE_CSC.OBJETO_CONTRATO, CPE_CSC.CSC_DATA_FIM, CASE WHEN CPE_CSC.CSC_DGCO IS NOT NULL THEN CPE_CSC.CSC_DGCO ELSE CPE_FINANCEIRO.DGCO_BB END AS CSC_DGCO, CPE_CSC.OBSERVACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME As FISCAL_DE_SERVICO, PESSOA1.NOME As FISCAL_ADM_DO_CONTRATO, PESSOA2.NOME As GESTOR_DO_CONTRATO, OCORRENCIA.ID_OCORRENCIA, PESSOA3.NOME As RESPONSAVEL, PESSOA3.USUARIO_REDE As USUARIO_RESPONSAVEL, CLASSE_SUB_PROCESSO.SIGLA, CPE_CSC.NUMERO_RC, Z_00143_ADIT_SOL.LIST_AD As TIPO_ADITAMENTO, CPE_FINANCEIRO.DGCO_BB From OCORRENCIA Left Join CLASSE_SUB_PROCESSO On CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = OCORRENCIA.ID_CLASSE_SUB_PROC_INI Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = CPE_CSC.FISCAL_DE_SERVICO Left Join PESSOA PESSOA1 On PESSOA1.ID_PESSOA = CPE_CSC.FISCAL_ADM_DO_CONTRATO Left Join PESSOA PESSOA2 On PESSOA2.ID_PESSOA = CPE_CSC.GESTOR_DO_CONTRATO Left Join PESSOA PESSOA3 On PESSOA3.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Left Join Z_00143_ADIT_SOL On OCORRENCIA.ID_OCORRENCIA = Z_00143_ADIT_SOL.ID_OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Where (CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO In (379) Or CLASSE_SUB_PROCESSO.SIGLA In ('ADT', 'ADITAMENTOSOL'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesSolicitacaoAditamento(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_ULT_ATUA, CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO, OCORRENCIA.DATA_HORA_SOL, CPE_CSC.OBJETO_CONTRATO, CPE_CSC.CSC_DATA_FIM, CASE WHEN CPE_CSC.CSC_DGCO IS NOT NULL THEN CPE_CSC.CSC_DGCO ELSE CPE_FINANCEIRO.DGCO_BB END AS CSC_DGCO, CPE_CSC.OBSERVACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME As FISCAL_DE_SERVICO, PESSOA1.NOME As FISCAL_ADM_DO_CONTRATO, PESSOA2.NOME As GESTOR_DO_CONTRATO, OCORRENCIA.ID_OCORRENCIA, PESSOA3.NOME As RESPONSAVEL, PESSOA3.USUARIO_REDE As USUARIO_RESPONSAVEL, CLASSE_SUB_PROCESSO.SIGLA, CPE_CSC.NUMERO_RC, Z_00143_ADIT_SOL.LIST_AD As TIPO_ADITAMENTO, CPE_FINANCEIRO.DGCO_BB From OCORRENCIA Left Join CLASSE_SUB_PROCESSO On CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = OCORRENCIA.ID_CLASSE_SUB_PROC_INI Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = CPE_CSC.FISCAL_DE_SERVICO Left Join PESSOA PESSOA1 On PESSOA1.ID_PESSOA = CPE_CSC.FISCAL_ADM_DO_CONTRATO Left Join PESSOA PESSOA2 On PESSOA2.ID_PESSOA = CPE_CSC.GESTOR_DO_CONTRATO Left Join PESSOA PESSOA3 On PESSOA3.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Left Join Z_00143_ADIT_SOL On OCORRENCIA.ID_OCORRENCIA = Z_00143_ADIT_SOL.ID_OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Where (CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO In (379) Or CLASSE_SUB_PROCESSO.SIGLA In ('ADT', 'ADITAMENTOSOL')) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



# R E V I S Õ E S   D E   O C
def listarRevisoesOrdensCompra():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.ID_OCORRENCIA, ORDEM_SERVICO.DESCRICAO_DETALHADA, CP_ORDEM_SERVICO.CNPJ, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CP_ORDEM_SERVICO.NUMERO_OC, CPE_CSC.CSC_DGCO, CPE_CSC.NUMERO_RC, ORDEM_SERVICO.JUSTIFICATIVA, CP_ORDEM_SERVICO.CPF, CPE_CSC.CSC_CPF, CPE_CSC.FISICA_JUDIRICA, CP_ORDEM_SERVICO.SIM_NAO, PESSOA.NOME As RESPONSAVEL, PESSOA.USUARIO_REDE As USUARIO_RESPONSAVEL, CLASSE_SUB_PROCESSO.SIGLA From OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On ORDEM_SERVICO.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Where (OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (395) Or CLASSE_SUB_PROCESSO.SIGLA In ('REVISAOOC'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesOrdemCompra(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, OCORRENCIA.ID_OCORRENCIA, ORDEM_SERVICO.DESCRICAO_DETALHADA, CP_ORDEM_SERVICO.CNPJ, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CP_ORDEM_SERVICO.NUMERO_OC, CPE_CSC.CSC_DGCO, CPE_CSC.NUMERO_RC, ORDEM_SERVICO.JUSTIFICATIVA, CP_ORDEM_SERVICO.CPF, CPE_CSC.CSC_CPF, CPE_CSC.FISICA_JUDIRICA, CP_ORDEM_SERVICO.SIM_NAO, PESSOA.NOME As RESPONSAVEL, PESSOA.USUARIO_REDE As USUARIO_RESPONSAVEL, CLASSE_SUB_PROCESSO.SIGLA From OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On ORDEM_SERVICO.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Where (OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (395) Or CLASSE_SUB_PROCESSO.SIGLA In ('REVISAOOC')) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



# P R O C E S S O S   A D M I N I S T R A T I V O S
def listarProcessosAdministrativos():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.SITUACAO, OCORRENCIA.NUMERO, CPE_HOMOLOGACAO.TIP_SOLDR, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME As RESPONSAVEL, PESSOA.USUARIO_REDE As USUARIO_RESPONSAVEL, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CPE_CSC.CSC_DGCO, CLASSE_SUB_PROCESSO.SIGLA, CPE_CSC.CSC_DATA_FIM As FIM_VIGENCIA, CPE_CSC.SIM_NAO1 As COMISSAO, CPE_CSC.OBSERVACAO, CPE_CSC.OBJETO_CONTRATO, PESSOA1.NOME As GESTOR, PESSOA2.NOME As FISCAL_ADM, PESSOA3.NOME As FISCAL_SERVICO From OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_HOMOLOGACAO On OCORRENCIA.ID_OCORRENCIA = CPE_HOMOLOGACAO.ID_OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On OCORRENCIA.ID_RESPONSAVEL = PESSOA.ID_PESSOA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Left Join PESSOA PESSOA1 On CPE_CSC.GESTOR_DO_CONTRATO = PESSOA1.ID_PESSOA Left Join PESSOA PESSOA2 On CPE_CSC.FISCAL_ADM_DO_CONTRATO = PESSOA2.ID_PESSOA Left Join PESSOA PESSOA3 On CPE_CSC.FISCAL_DE_SERVICO = PESSOA3.ID_PESSOA Where (OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (598) Or CLASSE_SUB_PROCESSO.SIGLA In ('PROCESSADM'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesProcessoAdministrativo(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.SITUACAO, OCORRENCIA.NUMERO, CPE_HOMOLOGACAO.TIP_SOLDR, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME As RESPONSAVEL, PESSOA.USUARIO_REDE As USUARIO_RESPONSAVEL, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CPE_CSC.CSC_DGCO, CLASSE_SUB_PROCESSO.SIGLA, CPE_CSC.CSC_DATA_FIM As FIM_VIGENCIA, CPE_CSC.SIM_NAO1 As COMISSAO, CPE_CSC.OBSERVACAO, CPE_CSC.OBJETO_CONTRATO, PESSOA1.NOME As GESTOR, PESSOA2.NOME As FISCAL_ADM, PESSOA3.NOME As FISCAL_SERVICO From OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_HOMOLOGACAO On OCORRENCIA.ID_OCORRENCIA = CPE_HOMOLOGACAO.ID_OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On OCORRENCIA.ID_RESPONSAVEL = PESSOA.ID_PESSOA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Left Join PESSOA PESSOA1 On CPE_CSC.GESTOR_DO_CONTRATO = PESSOA1.ID_PESSOA Left Join PESSOA PESSOA2 On CPE_CSC.FISCAL_ADM_DO_CONTRATO = PESSOA2.ID_PESSOA Left Join PESSOA PESSOA3 On CPE_CSC.FISCAL_DE_SERVICO = PESSOA3.ID_PESSOA Where (OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (598) Or CLASSE_SUB_PROCESSO.SIGLA In ('PROCESSADM')) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



# D I S T R A T O S   E   R E S C I S Õ E S
def listarDistratosRescisoes():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.SITUACAO, OCORRENCIA.NUMERO, CPE_CSC.NUMERO_DGCO, CPE_HOMOLOGACAO.TIP_SOLDR, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME As RESPONSAVEL, PESSOA.USUARIO_REDE As USUARIO_RESPONSAVEL, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CLASSE_SUB_PROCESSO.SIGLA, CPE_CSC.DEMANDANTE As AREA_DEMANDANTE, CPE_CSC.CSC_EMPRESA, CP_ORDEM_SERVICO.RESUMO As OBJETO, CP_ORDEM_SERVICO.DATA1 As VIGENCIA_INICIAL, CP_ORDEM_SERVICO.DATA2 As VIGENCIAL_FINAL, CP_ORDEM_SERVICO.MOTIVO As DESCRICAI_ORRENCIA, PESSOA1.NOME As FISCAL_SERVICO, PESSOA2.NOME As GESTOR_CONTRATO, CPE_CSC.DESCRICAO_DETALHADA, CPE_CONTRATOS02.DATA_ASSINATURA_C, CPE_CONTRATOS02.DATA_ENCERRAMENTO_C From OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_HOMOLOGACAO On OCORRENCIA.ID_OCORRENCIA = CPE_HOMOLOGACAO.ID_OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On OCORRENCIA.ID_RESPONSAVEL = PESSOA.ID_PESSOA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Left Join PESSOA PESSOA1 On CPE_CSC.FISCAL_DE_SERVICO = PESSOA1.ID_PESSOA Left Join PESSOA PESSOA2 On CPE_CSC.GESTOR_DO_CONTRATO = PESSOA2.ID_PESSOA Left Join CPE_CONTRATOS02 On OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA Where OCORRENCIA.ID_OCORRENCIA > 1690000 And (OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (659, 380) Or CLASSE_SUB_PROCESSO.SIGLA In ('423', 'DISTRATOERESCI', 'DISTRATOERESCISAO'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesDistratoRescisao(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.SITUACAO, OCORRENCIA.NUMERO, CPE_CSC.NUMERO_DGCO, CPE_HOMOLOGACAO.TIP_SOLDR, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME As RESPONSAVEL, PESSOA.USUARIO_REDE As USUARIO_RESPONSAVEL, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CLASSE_SUB_PROCESSO.SIGLA, CPE_CSC.DEMANDANTE As AREA_DEMANDANTE, CPE_CSC.CSC_EMPRESA, CP_ORDEM_SERVICO.RESUMO As OBJETO, CP_ORDEM_SERVICO.DATA1 As VIGENCIA_INICIAL, CP_ORDEM_SERVICO.DATA2 As VIGENCIAL_FINAL, CP_ORDEM_SERVICO.MOTIVO As DESCRICAI_ORRENCIA, PESSOA1.NOME As FISCAL_SERVICO, PESSOA2.NOME As GESTOR_CONTRATO, CPE_CSC.DESCRICAO_DETALHADA, CPE_CONTRATOS02.DATA_ASSINATURA_C, CPE_CONTRATOS02.DATA_ENCERRAMENTO_C From OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_HOMOLOGACAO On OCORRENCIA.ID_OCORRENCIA = CPE_HOMOLOGACAO.ID_OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On OCORRENCIA.ID_RESPONSAVEL = PESSOA.ID_PESSOA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Left Join PESSOA PESSOA1 On CPE_CSC.FISCAL_DE_SERVICO = PESSOA1.ID_PESSOA Left Join PESSOA PESSOA2 On CPE_CSC.GESTOR_DO_CONTRATO = PESSOA2.ID_PESSOA Left Join CPE_CONTRATOS02 On OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA Where OCORRENCIA.ID_OCORRENCIA > 1690000 And (OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (659, 380) Or CLASSE_SUB_PROCESSO.SIGLA In ('423', 'DISTRATOERESCI', 'DISTRATOERESCISAO')) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



# E N C E R R A M E N T O   C O N T R A T U A L
def listarEncerramentosContratuais():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_ULT_ATUA, CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO, OCORRENCIA.DATA_HORA_SOL, CPE_CSC.OBJETO_CONTRATO, CPE_CSC.CSC_DATA_FIM, CPE_CSC.CSC_DGCO, CPE_CSC.OBSERVACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME As FISCAL_DE_SERVICO, PESSOA1.NOME As FISCAL_ADM_DO_CONTRATO, PESSOA2.NOME As GESTOR_DO_CONTRATO, OCORRENCIA.ID_OCORRENCIA, PESSOA3.NOME As RESPONSAVEL, PESSOA3.ID_PESSOA, PESSOA3.USUARIO_REDE As USUARIO_RESPONSAVEL From OCORRENCIA Left Join CLASSE_SUB_PROCESSO On CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = OCORRENCIA.ID_CLASSE_SUB_PROC_INI Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = CPE_CSC.FISCAL_DE_SERVICO Left Join PESSOA PESSOA1 On PESSOA1.ID_PESSOA = CPE_CSC.FISCAL_ADM_DO_CONTRATO Left Join PESSOA PESSOA2 On PESSOA2.ID_PESSOA = CPE_CSC.GESTOR_DO_CONTRATO Left Join PESSOA PESSOA3 On PESSOA3.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Where (CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO In (536, 327) Or CLASSE_SUB_PROCESSO.SIGLA In ('AVSENCERRACONTRATO', 'AVISOENCERRACONT', 'ENCERRAMENTODECONTRATO'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesEncerramentoContratual(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_ULT_ATUA, CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO, OCORRENCIA.DATA_HORA_SOL, CPE_CSC.OBJETO_CONTRATO, CPE_CSC.CSC_DATA_FIM, CPE_CSC.CSC_DGCO, CPE_CSC.OBSERVACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME As FISCAL_DE_SERVICO, PESSOA1.NOME As FISCAL_ADM_DO_CONTRATO, PESSOA2.NOME As GESTOR_DO_CONTRATO, OCORRENCIA.ID_OCORRENCIA, PESSOA3.NOME As RESPONSAVEL, PESSOA3.ID_PESSOA, PESSOA3.USUARIO_REDE As USUARIO_RESPONSAVEL From OCORRENCIA Left Join CLASSE_SUB_PROCESSO On CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = OCORRENCIA.ID_CLASSE_SUB_PROC_INI Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = CPE_CSC.FISCAL_DE_SERVICO Left Join PESSOA PESSOA1 On PESSOA1.ID_PESSOA = CPE_CSC.FISCAL_ADM_DO_CONTRATO Left Join PESSOA PESSOA2 On PESSOA2.ID_PESSOA = CPE_CSC.GESTOR_DO_CONTRATO Left Join PESSOA PESSOA3 On PESSOA3.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Where (CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO In (536, 327) Or CLASSE_SUB_PROCESSO.SIGLA In ('AVSENCERRACONTRATO', 'AVISOENCERRACONT', 'ENCERRAMENTODECONTRATO')) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



# A T U A L I Z Ç Ã O   D E   D A D O S   B A N C Á R I O S
def listarAtualizacoesDeDadosBancarios():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.SITUACAO, OCORRENCIA.NUMERO, OCORRENCIA.DATA_HORA_ULT_ATUA, CPE_CSC.BANCO_NOME, CPE_CSC.AGENCIA_NUMERO, CPE_CSC.CSC_DIGITO_AGENCIA, CPE_CSC.CONTA_CORRENTE_NUMERO, CPE_CSC.CSC_CPF, CPE_CONTRATOS.OBS2, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CP_ORDEM_SERVICO.CNPJ_FORNECEDOR, CPE_CONTRATOS.OBS3, PESSOA.NOME As RESPONSAVEL, PESSOA.USUARIO_REDE As USUARIO_RESPONSAVEL, CLASSE_SUB_PROCESSO.SIGLA From OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_CONTRATOS On OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Where (OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (357) Or CLASSE_SUB_PROCESSO.SIGLA In ('ALTERARDADOSBANCARIOS', 'AUTORIZARALTDADOSBANC'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesAtualizacaoDeDadosBancarios(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.SITUACAO, OCORRENCIA.NUMERO, OCORRENCIA.DATA_HORA_ULT_ATUA, CPE_CSC.BANCO_NOME, CPE_CSC.AGENCIA_NUMERO, CPE_CSC.CSC_DIGITO_AGENCIA, CPE_CSC.CONTA_CORRENTE_NUMERO, CPE_CSC.CSC_CPF, CPE_CONTRATOS.OBS2, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CP_ORDEM_SERVICO.CNPJ_FORNECEDOR, CPE_CONTRATOS.OBS3, PESSOA.NOME As RESPONSAVEL, PESSOA.USUARIO_REDE As USUARIO_RESPONSAVEL, CLASSE_SUB_PROCESSO.SIGLA From OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_CONTRATOS On OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Where (OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (357) Or CLASSE_SUB_PROCESSO.SIGLA In ('ALTERARDADOSBANCARIOS', 'AUTORIZARALTDADOSBANC')) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



# A T E S T A D O S   D E   C A P A C I D A D E   T É C N I C A
def listarAtestadosCapacidadeTecnica():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_ULT_ATUA, ORDEM_SERVICO.DESCRICAO_DETALHADA, OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, CPE_FINANCEIRO.DGCO_BB, CP_ORDEM_SERVICO.NOME_FORNECEDOR, PESSOA.NOME As RESPONSAVEL, PESSOA.USUARIO_REDE As USUARIO_RESPONSAVEL, CLASSE_SUB_PROCESSO.SIGLA From OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Where (OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (348) Or CLASSE_SUB_PROCESSO.SIGLA In ('EMISSAOATESTADOFORNECEDOR', 'ATESTADOCAPTECFORNECEDOR'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesAtestadosDeCapacidadeTecnica(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.SITUACAO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_ULT_ATUA, ORDEM_SERVICO.DESCRICAO_DETALHADA, OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, CPE_FINANCEIRO.DGCO_BB, CP_ORDEM_SERVICO.NOME_FORNECEDOR, PESSOA.NOME As RESPONSAVEL, PESSOA.USUARIO_REDE As USUARIO_RESPONSAVEL, CLASSE_SUB_PROCESSO.SIGLA From OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Where (OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (348) Or CLASSE_SUB_PROCESSO.SIGLA In ('EMISSAOATESTADOFORNECEDOR', 'ATESTADOCAPTECFORNECEDOR')) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



# T E R M O S   D E S I G N A Ç Ã O
def buscarChamadosTermo():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CPE_FINANCEIRO1.DGCO_BB As DGCO, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO, CPE_CONTRATOS02.TIPO_DESIGNACAO_INTERV, CPE_CONTRATOS02.DESIGNA_TITU_OR_SUP, PESSOA.NOME As DESIGNADO, CLASSE_SUB_PROCESSO.SIGLA From OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO CPE_FINANCEIRO1 On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA Left Join CPE_CONTRATOS02 On OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Left Join PESSOA On PESSOA.ID_PESSOA = CASE WHEN REGEXP_LIKE(CP_ORDEM_SERVICO.FAVORECIDO_ALL, '^[0-9]+$') THEN TO_NUMBER(CP_ORDEM_SERVICO.FAVORECIDO_ALL) ELSE NULL END Where (OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (658, 637) Or CLASSE_SUB_PROCESSO.SIGLA In ('TERMOACEITEDESIGNACAOO', 'TERMOINTERVCONTRAT', 'TERMODEDESIGNACAO'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarTermosPorOs(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CPE_FINANCEIRO1.DGCO_BB As DGCO, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO, CPE_CONTRATOS02.TIPO_DESIGNACAO_INTERV, CPE_CONTRATOS02.DESIGNA_TITU_OR_SUP, PESSOA.NOME As DESIGNADO, CLASSE_SUB_PROCESSO.SIGLA From OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO CPE_FINANCEIRO1 On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA Left Join CPE_CONTRATOS02 On OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Left Join PESSOA On PESSOA.ID_PESSOA = CASE WHEN REGEXP_LIKE(CP_ORDEM_SERVICO.FAVORECIDO_ALL, '^[0-9]+$') THEN TO_NUMBER(CP_ORDEM_SERVICO.FAVORECIDO_ALL) ELSE NULL END Where (OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (658, 637) Or CLASSE_SUB_PROCESSO.SIGLA In ('TERMOACEITEDESIGNACAOO', 'TERMOINTERVCONTRAT', 'TERMODEDESIGNACAO')) AND OCORRENCIA.NUMERO LIKE '%{}%'".format(numeroOs))
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesTermo(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA As IDENTIFICADOR, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, OCORRENCIA.DATA_HORA_FIM_REAL As DATA_HORA_FIM_SOL, CPE_FINANCEIRO1.DGCO_BB As DGCO, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO, CPE_CONTRATOS02.TIPO_DESIGNACAO_INTERV, CPE_CONTRATOS02.DESIGNA_TITU_OR_SUP, PESSOA.NOME As DESIGNADO, CLASSE_SUB_PROCESSO.SIGLA From OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_FINANCEIRO CPE_FINANCEIRO1 On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA Left Join CPE_CONTRATOS02 On OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Left Join PESSOA On PESSOA.ID_PESSOA = CASE WHEN REGEXP_LIKE(CP_ORDEM_SERVICO.FAVORECIDO_ALL, '^[0-9]+$') THEN TO_NUMBER(CP_ORDEM_SERVICO.FAVORECIDO_ALL) ELSE NULL END Where (OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (658, 637) Or CLASSE_SUB_PROCESSO.SIGLA In ('TERMOACEITEDESIGNACAOO', 'TERMOINTERVCONTRAT', 'TERMODEDESIGNACAO')) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



# D E S I G N A Ç Ã O
def buscarChamadosDesignacao():
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.ID_OCORRENCIA AS IDENTIFICADOR, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, CPE_FINANCEIRO1.DGCO_BB AS DGCO, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO, CPE_CONTRATOS.COMBOBOX_6 AS tipo_designacao, CLASSE_SUB_PROCESSO.SIGLA, PESSOA.NOME AS SOLICITANTE, PESSOA1.NOME AS RESPONSAVEL, LISTAGG(Z_00143_GRID_DESIGNACAO.DGCO, '; ') WITHIN GROUP (ORDER BY NULL) AS DGCO_LISTA, LISTAGG(SUBSTR(Z_00143_GRID_DESIGNACAO.RAZAO_SOCIAL, 1, 59), '; ') WITHIN GROUP (ORDER BY NULL) AS RAZAO_SOCIAL_LISTA FROM OCORRENCIA LEFT JOIN CPE_FINANCEIRO ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CPE_FINANCEIRO CPE_FINANCEIRO1 ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA LEFT JOIN CLASSE_SUB_PROCESSO ON OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO LEFT JOIN CPE_CONTRATOS ON OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS.ID_OCORRENCIA LEFT JOIN PESSOA ON OCORRENCIA.ID_CLIENTE = PESSOA.ID_PESSOA LEFT JOIN PESSOA PESSOA1 ON OCORRENCIA.ID_RESPONSAVEL = PESSOA1.ID_PESSOA LEFT JOIN Z_00143_GRID_DESIGNACAO ON OCORRENCIA.ID_OCORRENCIA = Z_00143_GRID_DESIGNACAO.ID_OCORRENCIA WHERE (OCORRENCIA.ID_CLASSE_SUB_PROC_INI IN (654, 635)) OR (CLASSE_SUB_PROCESSO.SIGLA IN ('DESIGNACAOSISCONNN', 'DESIGNASISCCON2', 'DESIGNACAODEINTERVENIENTES')) GROUP BY OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, OCORRENCIA.DATA_HORA_FIM_REAL, CPE_FINANCEIRO1.DGCO_BB, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO, CPE_CONTRATOS.COMBOBOX_6, CLASSE_SUB_PROCESSO.SIGLA, PESSOA.NOME, PESSOA1.NOME")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesDesignacao(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.ID_OCORRENCIA AS IDENTIFICADOR, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, CPE_FINANCEIRO1.DGCO_BB AS DGCO, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO, CPE_CONTRATOS.COMBOBOX_6 AS tipo_designacao, CLASSE_SUB_PROCESSO.SIGLA, PESSOA.NOME AS SOLICITANTE, PESSOA1.NOME AS RESPONSAVEL, LISTAGG(Z_00143_GRID_DESIGNACAO.DGCO, '; ') WITHIN GROUP (ORDER BY NULL) AS DGCO_LISTA, LISTAGG(SUBSTR(Z_00143_GRID_DESIGNACAO.RAZAO_SOCIAL, 1, 59), '; ') WITHIN GROUP (ORDER BY NULL) AS RAZAO_SOCIAL_LISTA FROM OCORRENCIA LEFT JOIN CPE_FINANCEIRO ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CPE_FINANCEIRO CPE_FINANCEIRO1 ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO1.ID_OCORRENCIA LEFT JOIN CLASSE_SUB_PROCESSO ON OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO LEFT JOIN CPE_CONTRATOS ON OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS.ID_OCORRENCIA LEFT JOIN PESSOA ON OCORRENCIA.ID_CLIENTE = PESSOA.ID_PESSOA LEFT JOIN PESSOA PESSOA1 ON OCORRENCIA.ID_RESPONSAVEL = PESSOA1.ID_PESSOA LEFT JOIN Z_00143_GRID_DESIGNACAO ON OCORRENCIA.ID_OCORRENCIA = Z_00143_GRID_DESIGNACAO.ID_OCORRENCIA WHERE ((OCORRENCIA.ID_CLASSE_SUB_PROC_INI IN (654, 635)) OR (CLASSE_SUB_PROCESSO.SIGLA IN ('DESIGNACAOSISCONNN', 'DESIGNASISCCON2', 'DESIGNACAODEINTERVENIENTES'))) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"' GROUP BY OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, OCORRENCIA.DATA_HORA_FIM_REAL, CPE_FINANCEIRO1.DGCO_BB, CP_ORDEM_SERVICO.OBJETO_CONTRATACAO, CPE_CONTRATOS.COMBOBOX_6, CLASSE_SUB_PROCESSO.SIGLA, PESSOA.NOME, PESSOA1.NOME")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)

        
# A V A L I A Ç Ã O
def buscarChamadosAvaliacao():
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.ID_OCORRENCIA AS IDENTIFICADOR, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CPE_CSC.COLABORADOR AS AVALIADOR, CPE_CONTRATOS02.NOTA_AVALIACAO AS MEDIA_TRIMESTRAL, CPE_HOMOLOGACAO.DIAS AS ANO, CP_ORDEM_SERVICO.DIAS_PRAZO AS PERIODO, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, CPE_CONTRATOS02.COLABORADOR2 AS GESTOR, CPE_CSC1.CSC_DGCO, CPE_CONTRATOS02.NM_GERENCIA AS GERENCIA, CLASSE_SUB_PROCESSO.SIGLA, CPE_CONTRATOS02.TIPO_AVALIACAO FROM OCORRENCIA LEFT JOIN CPE_FINANCEIRO ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CPE_CSC ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA LEFT JOIN CPE_CONTRATOS02 ON OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA LEFT JOIN CPE_HOMOLOGACAO ON OCORRENCIA.ID_OCORRENCIA = CPE_HOMOLOGACAO.ID_OCORRENCIA LEFT JOIN CLASSE_SUB_PROCESSO ON OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO LEFT JOIN CPE_CSC CPE_CSC1 ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC1.ID_OCORRENCIA WHERE (OCORRENCIA.ID_CLASSE_SUB_PROC_INI IN (641, 655) OR CLASSE_SUB_PROCESSO.SIGLA IN ('AVALIAFISCASERVICOOO', 'AVFOR', 'AVALIFORNECEDORES'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesAvaliacao(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("SELECT OCORRENCIA.ID_OCORRENCIA AS IDENTIFICADOR, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, CP_ORDEM_SERVICO.NOME_FORNECEDOR, CPE_CSC.COLABORADOR AS AVALIADOR, CPE_CONTRATOS02.NOTA_AVALIACAO AS MEDIA_TRIMESTRAL, CPE_HOMOLOGACAO.DIAS AS ANO, CP_ORDEM_SERVICO.DIAS_PRAZO AS PERIODO, OCORRENCIA.DATA_HORA_FIM_REAL AS DATA_HORA_FIM_SOL, CPE_CONTRATOS02.COLABORADOR2 AS GESTOR, CPE_CSC1.CSC_DGCO, CPE_CONTRATOS02.NM_GERENCIA AS GERENCIA, CLASSE_SUB_PROCESSO.SIGLA, CPE_CONTRATOS02.TIPO_AVALIACAO FROM OCORRENCIA LEFT JOIN CPE_FINANCEIRO ON OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA LEFT JOIN CP_ORDEM_SERVICO ON OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA LEFT JOIN CPE_CSC ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA LEFT JOIN CPE_CONTRATOS02 ON OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA LEFT JOIN CPE_HOMOLOGACAO ON OCORRENCIA.ID_OCORRENCIA = CPE_HOMOLOGACAO.ID_OCORRENCIA LEFT JOIN CLASSE_SUB_PROCESSO ON OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO LEFT JOIN CPE_CSC CPE_CSC1 ON OCORRENCIA.ID_OCORRENCIA = CPE_CSC1.ID_OCORRENCIA WHERE (OCORRENCIA.ID_CLASSE_SUB_PROC_INI IN (641, 655) OR CLASSE_SUB_PROCESSO.SIGLA IN ('AVALIAFISCASERVICOOO', 'AVFOR', 'AVALIFORNECEDORES')) AND OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)

# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# OLD STUFFS




# ONBOARD
def listarOnBoard():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.DATA_HORA_ULT_ATUA, CP_ORDEM_SERVICO.NOME_FORNECEDOR, NVL(CPE_FINANCEIRO.DGCO_BB, CPE_CSC.CSC_DGCO) As CSC_DGCO, PESSOA.NOME As RESPONSAVEL, PESSOA.USUARIO_REDE As USUARIO_RESPONSAVEL, CPE_CSC.SIM_NAO3 As COMISSAO, CPE_CSC.OBS21 As OBJETO, PESSOA1.NOME As ANALISTA_TITULAR, CPE_CONTRATOS02.MATRICULA_ANA_TITU As MATRICULA_TITULAR, PESSOA2.NOME As ANALISTA_SUPLENTE, CPE_CONTRATOS02.MATRICULA_ANA_SUP As MATRICULA_SUPLENTE, CLASSE_SUB_PROCESSO.SIGLA From OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On ORDEM_SERVICO.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CPE_CONTRATOS02 On OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA Left Join PESSOA PESSOA1 On PESSOA1.ID_PESSOA = CPE_CONTRATOS02.ANALISTA_CONTRATO_TITU Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Left Join PESSOA PESSOA2 On PESSOA2.ID_PESSOA = CPE_CONTRATOS02.ANALISTA_CONTRATO_SUP Where (OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (625) Or CLASSE_SUB_PROCESSO.SIGLA In ('ONBOARD'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesOnBoard(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.DATA_HORA_ULT_ATUA, CP_ORDEM_SERVICO.NOME_FORNECEDOR, NVL(CPE_FINANCEIRO.DGCO_BB, CPE_CSC.CSC_DGCO) As CSC_DGCO, PESSOA.NOME As RESPONSAVEL, PESSOA.USUARIO_REDE As USUARIO_RESPONSAVEL, CPE_CSC.SIM_NAO3 As COMISSAO, CPE_CSC.OBS21 As OBJETO, PESSOA1.NOME As ANALISTA_TITULAR, CPE_CONTRATOS02.MATRICULA_ANA_TITU As MATRICULA_TITULAR, PESSOA2.NOME As ANALISTA_SUPLENTE, CPE_CONTRATOS02.MATRICULA_ANA_SUP As MATRICULA_SUPLENTE, CLASSE_SUB_PROCESSO.SIGLA From OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On ORDEM_SERVICO.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CPE_CONTRATOS02 On OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA Left Join PESSOA PESSOA1 On PESSOA1.ID_PESSOA = CPE_CONTRATOS02.ANALISTA_CONTRATO_TITU Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Left Join PESSOA PESSOA2 On PESSOA2.ID_PESSOA = CPE_CONTRATOS02.ANALISTA_CONTRATO_SUP Where (OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (625) Or CLASSE_SUB_PROCESSO.SIGLA In ('ONBOARD')) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)





# GARANTIA
def listarGarantia():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.NUMERO, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.SITUACAO, OCORRENCIA.ID_OCORRENCIA, NVL(CPE_FINANCEIRO.DGCO_BB, CPE_CSC.CSC_DGCO) As CSC_DGCO, PESSOA.NOME As RESPONSAVEL, PESSOA.USUARIO_REDE As USUARIO_RESPONSAVEL, CP_ORDEM_SERVICO.SIM_NAO As POSSUI_GARANTIA, CLASSE_SUB_PROCESSO.SIGLA From OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On ORDEM_SERVICO.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CPE_CONTRATOS02 On OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA Left Join PESSOA PESSOA1 On PESSOA1.ID_PESSOA = CPE_CONTRATOS02.ANALISTA_CONTRATO_TITU Left Join PESSOA PESSOA2 On PESSOA2.ID_PESSOA = CPE_CONTRATOS02.ANALISTA_CONTRATO_SUP Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Where (OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (404) Or CLASSE_SUB_PROCESSO.SIGLA In ('ANGACOL', 'ANAGARANCONT'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def buscarDetalhesGarantia(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.ID_CLASSE_SUB_PROC_INI, OCORRENCIA.DATA_HORA_ULT_ATUA, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, OCORRENCIA.ID_OCORRENCIA, NVL(CPE_FINANCEIRO.DGCO_BB, CPE_CSC.CSC_DGCO) As CSC_DGCO, PESSOA.NOME As RESPONSAVEL, PESSOA.USUARIO_REDE As USUARIO_RESPONSAVEL, CP_ORDEM_SERVICO.SIM_NAO As POSSUI_GARANTIA, CLASSE_SUB_PROCESSO.SIGLA From OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On ORDEM_SERVICO.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CPE_CONTRATOS02 On OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS02.ID_OCORRENCIA Left Join PESSOA PESSOA1 On PESSOA1.ID_PESSOA = CPE_CONTRATOS02.ANALISTA_CONTRATO_TITU Left Join PESSOA PESSOA2 On PESSOA2.ID_PESSOA = CPE_CONTRATOS02.ANALISTA_CONTRATO_SUP Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Where (OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (404) Or CLASSE_SUB_PROCESSO.SIGLA In ('ANGACOL', 'ANAGARANCONT')) And OCORRENCIA.NUMERO = '"+str(numeroOs)+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e) 





def enviaDadosGestoresUor():
    try:
        result_table2 = DB.ExecuteDataTable("SELECT MAX(matricula_sup_nivel1) AS MATRICULA_GESTOR, f.numero_subcr_nivel1 AS NUMERO, MAX(f.descricao_subcr_nivel1) AS DESCRICAO, MAX(c.scr_sigla) AS SIGLA FROM CAD_FUNCIONARIO_V F Left Join cob_gl_centro c ON c.scr = f.numero_subcr_nivel1 WHERE f.matricula_sup_nivel1 != ' ' GROUP BY f.numero_subcr_nivel1")
        
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)




def enviaDadosAnalisePB(matriculaCondutor, situacao):
    try:
        if matriculaCondutor != "0":
            if situacao == "todos":
                result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ASSUNTO, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME, CP_PESSOA.MATRICULA From OCORRENCIA Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_CLIENTE Left Join CP_PESSOA On PESSOA.ID_PESSOA = CP_PESSOA.ID_PESSOA Where CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = 425 And CP_PESSOA.MATRICULA = '"+matriculaCondutor+"' Order By OCORRENCIA.NUMERO")
            else:
                result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ASSUNTO, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME, CP_PESSOA.MATRICULA From OCORRENCIA Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_CLIENTE Left Join CP_PESSOA On PESSOA.ID_PESSOA = CP_PESSOA.ID_PESSOA Where CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = 425 And CP_PESSOA.MATRICULA = '"+matriculaCondutor+"' And OCORRENCIA.SITUACAO = '"+situacao+"' Order By OCORRENCIA.NUMERO")    
        else:
            if situacao == "todos":
                result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ASSUNTO, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME, CP_PESSOA.MATRICULA From OCORRENCIA Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_CLIENTE Left Join CP_PESSOA On PESSOA.ID_PESSOA = CP_PESSOA.ID_PESSOA Where CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = 425 Order By OCORRENCIA.NUMERO")
            else:
                result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ASSUNTO, OCORRENCIA.NUMERO, OCORRENCIA.SITUACAO, ORDEM_SERVICO.DESCRICAO_DETALHADA, PESSOA.NOME, CP_PESSOA.MATRICULA From OCORRENCIA Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_CLIENTE Left Join CP_PESSOA On PESSOA.ID_PESSOA = CP_PESSOA.ID_PESSOA Where CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO = 425 And OCORRENCIA.SITUACAO = '"+situacao+"' Order By OCORRENCIA.NUMERO")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



def enviaDadosContratacao():
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.SITUACAO, OCORRENCIA.NUMERO, ORDEM_SERVICO.DESCRICAO_DETALHADA As OBJETO_CONTRATACAO, PESSOA.NOME As RESPONSAVEL, PESSOA.USUARIO_REDE As USUARIO_RESPONSAVEL, CPE_CONTRATOS.NUMERO_NOTA_TECNICA, CP_ORDEM_SERVICO.FAVORECIDO_TODOS As ASSESSOR_ANALISTA, CPE_CONTRATOS.FORNECEDOR_CONTRATADO, CPE_CONTRATOS.NUMERO_DO_DGCO, CPE_CSC.FISCAL_ADM_DO_CONTRATO, CPE_CSC.FISCAL_DE_SERVICO, CPE_CSC.GESTOR_DO_CONTRATO, CPE_CSC.OBJETO_CONTRATO, CPE_CSC.NUMERO_RC, CPE_CSC.TE_MODALIDADE_CONTRATACAO As MODALIDADE_CONTRATACAO, CPE_CSC.CSC_DATA_FIM As DATA_FIM_VIGENCIA_ATUAL, CPE_CSC.CSC_DGCO As DGCO, CPE_CSC.OBSERVACAO From OCORRENCIA Left Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = ORDEM_SERVICO.ID_OCORRENCIA Left Join PESSOA On OCORRENCIA.ID_RESPONSAVEL = PESSOA.ID_PESSOA Left Join CPE_CONTRATOS On OCORRENCIA.ID_OCORRENCIA = CPE_CONTRATOS.ID_OCORRENCIA Left Join CP_ORDEM_SERVICO On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Where OCORRENCIA.ID_CLASSE_SUB_PROC_INI = 347")

        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



def enviaDadosDue():
    try:
        result_table2 = DB.ExecuteDataTable("Select CP_ORDEM_SERVICO.CNPJ As CNPJ, CP_ORDEM_SERVICO.SIM_NAO As NECESSARIO_BCK_CHECK, CP_ORDEM_SERVICO.ACAO_TOMADA As JUSTIFICATIVA, OCORRENCIA.ASSUNTO As ASSUNTO, CP_ORDEM_SERVICO.NOME_FORNECEDOR As RAZAO_SOCIAL, CPE_CONTRATOS.OBS5 As INFO_COMPLEMENTARES, CPE_CSC.CSC_VALOR1_A As VALOR_ARREMATADO, CPE_CSC.DIRETORIA_GERENCIA As DIRETORIA_GERENCIA, CPE_CONTRATOS.DIVISAO_DUEDILIGENCE As AREA, CPE_CSC.FUNDAMENTACAO As FUDAMENTACAO, CPE_CONTRATOS.MODALIDADE_DE_CONTRATACAO As MODALIDADE_CONTRAT, CPE_CSC.NUMERO_DGCO As DGCO, CPE_FINANCEIRO.OBJETO_QUALIF As OBJ_RESUMIDO, CPE_DESLOCAMENTO.VALOR_DESPESAS As SOMATORIO_CONTRATACAO, CPE_FINANCEIRO.VALOR_QUALIF As VALOR_CONTRATACAO, CPE_CSC.OBS6 As AJUSTES_NECESSARIOS, CPE_CSC.DATA_HORA_FIM As DATA_ANALISE, CPE_CONTRATOS.GRAUDERISCO_DUEDILIGENCE As GRAU_DE_RISCO, CPE_CSC.OBS21 As ANALISE_DISUP, CPE_CSC.SIM_NAO1 As GRANDE_EXPOSICAOBBTS, OCORRENCIA.ID_CLASSE_SUB_PROC As ID_OCORRENCIA, CPE_DESLOCAMENTO.VALOR_PASSAGEM As VALOR_ADITIVO1, OCORRENCIA.NUMERO, OCORRENCIA.DATA_HORA_CRIACAO, OCORRENCIA.SITUACAO, OCORRENCIA.ID_OCORRENCIA, OCORRENCIA.DATA_HORA_SOL, PESSOA.NOME, PESSOA1.NOME As GESTOR_DEMANDANTE, PESSOA2.NOME As RESPONSAVEL_AREA_CLIENTE From CP_ORDEM_SERVICO Left Join OCORRENCIA On OCORRENCIA.ID_OCORRENCIA = CP_ORDEM_SERVICO.ID_OCORRENCIA Left Join CPE_CONTRATOS On CP_ORDEM_SERVICO.ID_OCORRENCIA = CPE_CONTRATOS.ID_OCORRENCIA Left Join CPE_CSC On CPE_CONTRATOS.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Left Join CPE_FINANCEIRO On CPE_CSC.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join CPE_DESLOCAMENTO On CPE_FINANCEIRO.ID_OCORRENCIA = CPE_DESLOCAMENTO.ID_OCORRENCIA Left Join PESSOA On PESSOA.ID_PESSOA = OCORRENCIA.ID_RESPONSAVEL Left Join PESSOA PESSOA1 On PESSOA1.ID_PESSOA = CPE_CSC.TE_NOME_EMPREGADO Left Join PESSOA PESSOA2 On CP_ORDEM_SERVICO.FAVORECIDO_COBRA = PESSOA2.ID_PESSOA Where OCORRENCIA.ID_CLASSE_SUB_PROC = 534 Order By OCORRENCIA.NUMERO")

        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def enviaDadosCad():
    try:
        # ExecuteReader retorna um conjunto de resultados
        result_table2 = DB.ExecuteDataTable("Select F.status_matricula As STATUS_MATRICULA, F.nome As NOME, F.matricula As MATRICULA, F.gestor_posicao As GESTOR_POSICAO, F.cargo_funcional As CARGO_FUNCIONAL, F.CARGO,  F.funcao_gratificada As FUNCAO_GRATIFICADA,F.supervisor As SUPERVISOR, F.organizacao As ORGANIZACAO, F.unidade_negocio As UNIDADE_NEGOCIO, F.local_cidade As LOCAL_CIDADE,F.local_estado As LOCAL_ESTADO, F.numero_subcr_nivel1 As UOR_DIVISAO, F.descricao_subcr_nivel1 As DESCRICAO_DIVISAO, F.numero_subcr_nivel2 As UOR_GERENCIA,F.descricao_subcr_nivel2 As DESCRICAO_GERENCIA, F.numero_subcr_nivel3 As UOR_DIRETORIA, F.descricao_subcr_nivel3 As DESCRICAO_DIRETORIA, cp.DATA_NASCIMENTO As NASCIMENTO, cp.DATA_DE_ADMISSAO As ADMISSAO, P.EMAIL As EMAIL, P.USUARIO_REDE As USUARIO, P.BLOQUEADO As BLOQUEADO, c.scr_sigla As SIGLA_DIVISAO, c2.scr_sigla As SIGLA_GERENCIA, c3.scr_sigla As SIGLA_DIRETORIA From CAD_FUNCIONARIO_V F Inner Join cp_pessoa cp On F.matricula = cp.matricula Inner Join PESSOA P On cp.ID_PESSOA = P.id_pessoa Inner Join cob_gl_centro c On c.scr = F.numero_subcr_nivel1 Inner Join cob_gl_centro c2 On c2.scr = F.numero_subcr_nivel2 Inner Join cob_gl_centro c3 On c3.scr = F.numero_subcr_nivel3 Where f.CARGO_FUNCIONAL not in ('PRESTADOR DE SERVICO') And f.CARGO_FUNCIONAL IS NOT NULL Order By f.nome")
        
            
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data

    # Serializar a lista de pessoas para JSON
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)


def enviaDadosDiv():
    try:
        
        #ExecuteReader retorna um conjunto de resultados
        result_table2 = DB.ExecuteDataTable("SELECT DISTINCT matricula_sup_nivel1 as MATRICULA_GESTOR, f.numero_subcr_nivel1 As NUMERO, f.descricao_subcr_nivel1 As DESCRICAO, c.scr_sigla As SIGLA FROM CAD_FUNCIONARIO_V F Left Join cob_gl_centro c on c.scr = f.numero_subcr_nivel1")
        
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



# R E L A T Ó R I O   D A   G E R A L
def listarChamadosAditamentosGeral():
    try:
        result_table2 = DB.ExecuteDataTable("Select CPE_FINANCEIRO.DGCO_BB As DGCO, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL As DATA_HORA_SOLICITACAO, OCORRENCIA.DATA_HORA_ULT_ATUA, PESSOA.NOME As SOLICITANTE, PESSOA1.NOME As CONDUTOR, OCORRENCIA.SITUACAO, Z_00143_ADIT_SOL.LIST_AD As LIST_AD, OCORRENCIA.NUMERO, CLASSE_SUB_PROCESSO.SIGLA, CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO From OCORRENCIA Left Join CPE_FINANCEIRO On OCORRENCIA.ID_OCORRENCIA = CPE_FINANCEIRO.ID_OCORRENCIA Left Join PESSOA On OCORRENCIA.ID_CLIENTE = PESSOA.ID_PESSOA Left Join PESSOA PESSOA1 On OCORRENCIA.ID_RESPONSAVEL = PESSOA1.ID_PESSOA Left Join Z_00143_ADIT_SOL On OCORRENCIA.ID_OCORRENCIA = Z_00143_ADIT_SOL.ID_OCORRENCIA Left Join CLASSE_SUB_PROCESSO On OCORRENCIA.ID_CLASSE_SUB_PROC_INI = CLASSE_SUB_PROCESSO.ID_CLASSE_SUB_PROCESSO Where CPE_FINANCEIRO.DGCO_BB Is Not Null And (OCORRENCIA.ID_CLASSE_SUB_PROC_INI In (379) Or CLASSE_SUB_PROCESSO.SIGLA In ('ADT', 'ADITAMENTOSOL'))")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)




def realizarReservaDgco(fisica_juridica, cpf_cnpj, razao_social, descricao, matricula_solicitante, objeto):
    try:
        matriculaFiscalServ = matricula_solicitante
        id = 0
        colaboradores4 = DB.ExecuteDataTable("Select PESSOA.ID_PESSOA, PESSOA.NOME, CP_PESSOA.MATRICULA From PESSOA Inner Join CP_PESSOA On PESSOA.ID_PESSOA = CP_PESSOA.ID_PESSOA Where CP_PESSOA.MATRICULA = '" + matriculaFiscalServ.ToString()+"'")
 
        
        for row in colaboradores4.Rows:
            id = row["ID_PESSOA"]
        
        # Corrigido o argumento do assunto
        novaOS = OrdemServico.Nova(OrdemServico.Carrega('Numero', 589), "SOLICITRESERVDG", "RESERVDGCO", "Solicitação de Reserva DGCO - Dilic", Servico.Carrega(998), Pessoa.Carrega(id), Pessoa.Carrega(26709))
        
        novaOS.SetCustom('COMBOBOX1', 'Fornecedor')
        novaOS.DescricaoDetalhada = descricao
        
        novaOS.SetCustom('RAZAO_SOCIAL_CLIENTE', razao_social)
        novaOS.SetCustom('OBJETO_CONTRATACAO', objeto.ToString())
        
        if fisica_juridica == 'fisica':
            novaOS.SetCustom('CSC_CPF', cpf_cnpj)
            novaOS.ModificaCampoFormularioVisivel('CSC_CPF', True)
            novaOS.ModificaCampoFormularioVisivel('CNPJ', False)
            novaOS.SetCustom('JURIDICA_FISICA', 'Pessoa Física')
        else:
            novaOS.SetCustom('CNPJ', cpf_cnpj)
            novaOS.ModificaCampoFormularioVisivel('CNPJ', True)
            novaOS.ModificaCampoFormularioVisivel('CSC_CPF', False)
            novaOS.SetCustom('JURIDICA_FISICA', 'Pessoa Jurídica')
        
        
        novaOS.Salva()
        novaOS.AvancaAtividade()
        # Serializando o tipo de novaOS
        json_data = JsonConvert.SerializeObject([str(novaOS.Numero)])
        return json_data

    except Exception as e:
        return e.ToString()
        
        
def buscarDgco(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select CPE_CSC.CSC_DGCO From OCORRENCIA Inner Join CPE_CSC On OCORRENCIA.ID_OCORRENCIA = CPE_CSC.ID_OCORRENCIA Where OCORRENCIA.NUMERO = '"+numeroOs+"'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)



        
def encaminharOs(os, idPessoa):
    try:
        lista = Utils.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA, ORDEM_SERVICO.ID_OCORRENCIA, OCORRENCIA.NUMERO From OCORRENCIA Inner Join ORDEM_SERVICO On ORDEM_SERVICO.ID_OCORRENCIA = OCORRENCIA.ID_OCORRENCIA Where OCORRENCIA.NUMERO ='" + os + "'")

        idOcorrencia = 0
        for linha in lista.Rows:
            idOcorrencia = linha["ID_OCORRENCIA"]
               
        chamado = OrdemServico.Carrega(Convert.ToInt32(idOcorrencia))

        
        idCliente = idPessoa
        
        
        chamado.Favorecido = Pessoa.Carrega(Convert.ToInt32(idCliente))
        chamado.Responsavel = chamado.Favorecido

        chamado.Salva()
        
        
        return JsonConvert.SerializeObject(True)
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)
    



def enviaDadosColaborador():
    try:
        # ExecuteReader retorna um conjunto de resultados
        result_table2 = DB.ExecuteDataTable("Select PESSOA.ID_PESSOA, PESSOA.NOME, PESSOA.USUARIO_REDE, CP_PESSOA.MATRICULA, PESSOA.ATIVO From PESSOA Left Join CP_PESSOA On PESSOA.ID_PESSOA = CP_PESSOA.ID_PESSOA Order By PESSOA.NOME,  PESSOA.ID_PESSOA")
        

        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data

        # Serializar a lista de pessoas para JSON
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)
        
        

        
def validarOrdemServico(numeroOs):
    try:
        result_table2 = DB.ExecuteDataTable("Select OCORRENCIA.NUMERO, OCORRENCIA.ASSUNTO, OCORRENCIA.DATA_HORA_SOL, OCORRENCIA.DATA_HORA_FIM_REAL, OCORRENCIA.MOTIVO_CANCELAMENTO, OCORRENCIA.ID_RESPONSAVEL, OCORRENCIA.SITUACAO From OCORRENCIA  Where OCORRENCIA.NUMERO = '" + numeroOs + "'")
        
        json_data = JsonConvert.SerializeObject(result_table2)
        return json_data
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)
     
   
def alterarSituacao(situacao, os, motivo):
    try:
        

        lista = Utils.ExecuteDataTable("Select OCORRENCIA.ID_OCORRENCIA, ORDEM_SERVICO.ID_OCORRENCIA, OCORRENCIA.NUMERO From OCORRENCIA Inner Join ORDEM_SERVICO On ORDEM_SERVICO.ID_OCORRENCIA = OCORRENCIA.ID_OCORRENCIA Where OCORRENCIA.NUMERO ='" + os + "'")

        idOcorrencia = 0
        for linha in lista.Rows:
            idOcorrencia = linha["ID_OCORRENCIA"]
               
        chamado = OrdemServico.Carrega(Convert.ToInt32(idOcorrencia))

        if situacao == "Aberto":
            chamado.Situacao = "Aberto"
        elif situacao == "FinalizadaSucesso":
            chamado.Situacao = "FinalizadaSucesso"
        elif situacao == "Cancelado":
            if motivo != '':
                chamado.Cancela(motivo.ToString())
            else:
                chamado.Cancela('OS Cancelada com Sucesso!')
        else:
            raise Exception("Situação inválida.")

        chamado.Salva()
        
        
        return JsonConvert.SerializeObject(True)
    except Exception as e:
        return "Erro ao executar a consulta: " + str(e)
