# Teste_Uniforme_EPI
# Caminho: Catálogo > Biblioteca de scripts > Teste_Uniforme_EPI
# Fonte: Gestão_de_Pessoas_-_Benefícios_Versão_90_Reembolso.xml

if FormularioRegistro["CODIGO"].Valor == "UNIF-000017":
    FormularioRegistro["DESCRICAO"].Valor = "T-50 CAMISA TIPO POLO MASCULINA PIQUET AZUL MARINHO PANTONE 2758C (CMYK100/83/0/47) COM BOLSO NO LADO ESQUERDO DE QUEM VESTE E LOGOMARCA BBTS(8,5CM CONFORME IDENTIDADE VISUAL BBTS) BORDADA A 1CM ACIMA DO BOLSO (MASCULINA)"
    
    
    
    
if FormularioRegistro["CODIGO"].Valor == "UNIF-000050":
    FormularioRegistro["DESCRICAO"].Valor = "T-50 CAMISA TIPO POLO FEMININA PIQUET AZUL MARINHO PANTONE 2758C (CMYK100/83/0/47) COM BOLSO NO LADO ESQUERDO DE QUEM VESTE E LOGOMARCA BBTS(8,5CM CONFORME IDENTIDADE VISUAL BBTS) BORDADA A 1CM ACIMA DO BOLSO ( FEMININA)"
    
    
    
    
if FormularioRegistro["CODIGO"].Valor == "UNIF-000025":
    FormularioRegistro["DESCRICAO"].Valor = "T- 50 CAMISA MASCULINA JEANS MANGA LONGA NA COR AZUL MARINHO (82 ALGODAO E 18 POLIESTER) COM BOTOES, BOLSO NO LADO ESQUERDO"
    
    
    
    
if FormularioRegistro["CODIGO"].Valor == "UNIF-000051":
    FormularioRegistro["DESCRICAO"].Valor = "T- 50 CAMISA FEMININA JEANS MANGA LONGA NA COR AZUL MARINHO (82 ALGODAO E 18 POLIESTER) COM BOTOES, BOLSO NO LADO ESQUERDO "

    
    
    
if FormularioRegistro["CODIGO"].Valor == "UNIF-000023":
    FormularioRegistro["DESCRICAO"].Valor = "T-50 JAQUETA BBTS NA COR AZUL MARINHO PANTONE 2758 C (CMYK 100/83/0/47) E LOGOMARCA BBTS BORDADA (8,5 CM) EM HORIZONTAL NO LADO ESQUERDO DE QUE VESTE"
